from . import (
    capabilities,
    atlas_reports,
    attributes,
    cartography,
    data_sources,
    dev_tools,
    diagnostics,
    environment,
    expressions,
    export_layout,
    get_layer_info,
    get_logs,
    get_project_info,
    gis_tools,
    jobs,
    layer_tree,
    layouts,
    list_layers,
    load_layers,
    plugin_tools,
    platform,
    processing_inventory,
    raster,
    run_processing,
    selection,
    symbology,
    status,
    user_profile,
    workflows,
)


def register_actions(registry):
    registry.register("status", status.handle)
    registry.register("get_capabilities", capabilities.handle)
    registry.register("get_qgis_environment", environment.handle)
    registry.register("get_bridge_config", status.bridge_config)
    registry.register("list_layers", list_layers.handle)
    registry.register("list_project_layers", list_layers.handle)
    registry.register("load_vector_layer", load_layers.handle)
    registry.register("get_project_info", get_project_info.handle)
    registry.register("get_project_crs", get_project_info.project_crs)
    registry.register("get_layer_info", get_layer_info.handle)
    registry.register("diagnose_crs", gis_tools.diagnose_crs)
    registry.register("validate_geometries", gis_tools.validate_geometries)
    registry.register("fix_geometries", gis_tools.fix_geometries)
    registry.register("buffer", gis_tools.buffer)
    registry.register("clip", gis_tools.clip)
    registry.register("dissolve", gis_tools.dissolve)
    registry.register("reproject_layer", gis_tools.reproject_layer)
    registry.register("export_layer", gis_tools.export_layer)
    registry.register("intersection", gis_tools.intersection)
    registry.register("union", gis_tools.union)
    registry.register("difference", gis_tools.difference)
    registry.register("centroids", gis_tools.centroids)
    registry.register("multipart_to_singleparts", gis_tools.multipart_to_singleparts)
    registry.register("count_points_in_polygon", gis_tools.count_points_in_polygon)
    registry.register("load_raster_layer", raster.load_raster_layer)
    registry.register("raster_info", raster.raster_info)
    registry.register("raster_band_statistics", raster.raster_band_statistics)
    registry.register("raster_metadata_report", raster.raster_metadata_report)
    registry.register("raster_reproject", raster.raster_reproject)
    registry.register("raster_clip_by_extent", raster.raster_clip_by_extent)
    registry.register("raster_clip_by_mask", raster.raster_clip_by_mask)
    registry.register("raster_slope", raster.raster_slope)
    registry.register("raster_aspect", raster.raster_aspect)
    registry.register("raster_hillshade", raster.raster_hillshade)
    registry.register("raster_contours", raster.raster_contours)
    registry.register("raster_polygonize", raster.raster_polygonize)
    registry.register("get_user_profile", user_profile.get_user_profile)
    registry.register("set_user_profile", user_profile.set_user_profile)
    registry.register("clear_user_profile", user_profile.clear_user_profile)
    registry.register("plan_workflow", workflows.plan_workflow)
    registry.register("dry_run_workflow", workflows.dry_run_workflow)
    registry.register("execute_workflow", workflows.execute_workflow)
    registry.register("save_workflow_template", workflows.save_workflow_template)
    registry.register("list_workflow_templates", workflows.list_workflow_templates)
    registry.register("run_workflow_template", workflows.run_workflow_template)
    registry.register("start_job", jobs.start_job)
    registry.register("get_job_status", jobs.get_job_status)
    registry.register("get_job_result", jobs.get_job_result)
    registry.register("list_jobs", jobs.list_jobs)
    registry.register("cancel_job", jobs.cancel_job)
    registry.register("job_logs", jobs.job_logs)
    registry.register("clear_finished_jobs", jobs.clear_finished_jobs)
    registry.register("run_processing_job", jobs.run_processing_job)
    registry.register("run_workflow_job", jobs.run_workflow_job)
    registry.register("run_raster_job", jobs.run_raster_job)
    registry.register("run_map_export_job", jobs.run_map_export_job)
    registry.register("create_atlas", atlas_reports.create_atlas)
    registry.register("configure_atlas_coverage_layer", atlas_reports.configure_atlas_coverage_layer)
    registry.register("set_atlas_filter_expression", atlas_reports.set_atlas_filter_expression)
    registry.register("set_atlas_sort_expression", atlas_reports.set_atlas_sort_expression)
    registry.register("export_atlas_pdf", atlas_reports.export_atlas_pdf)
    registry.register("export_atlas_images", atlas_reports.export_atlas_images)
    registry.register("generate_map_book", atlas_reports.generate_map_book)
    registry.register("create_report", atlas_reports.create_report)
    registry.register("add_report_section", atlas_reports.add_report_section)
    registry.register("export_report_pdf", atlas_reports.export_report_pdf)
    registry.register("export_report_html", atlas_reports.export_report_html)
    registry.register("generate_workflow_report_pdf", atlas_reports.generate_workflow_report_pdf)
    registry.register("generate_analysis_report", atlas_reports.generate_analysis_report)
    registry.register("inspect_data_source", data_sources.inspect_data_source)
    registry.register("broken_data_source_report", data_sources.broken_data_source_report)
    registry.register("repair_data_source_path", data_sources.repair_data_source_path)
    registry.register("list_ogc_connections", data_sources.list_ogc_connections)
    registry.register("inspect_ogc_service", data_sources.inspect_ogc_service)
    registry.register("validate_service_url", data_sources.validate_service_url)
    registry.register("test_service_connection", data_sources.test_service_connection)
    registry.register("load_wms_layer", data_sources.load_wms_layer)
    registry.register("load_wfs_layer", data_sources.load_wfs_layer)
    registry.register("load_xyz_tile_layer", data_sources.load_xyz_tile_layer)
    registry.register("load_arcgis_rest_layer", data_sources.load_arcgis_rest_layer)
    registry.register("load_gpx", data_sources.load_gpx)
    registry.register("list_gpx_layers", data_sources.list_gpx_layers)
    registry.register("summarize_gpx_track", data_sources.summarize_gpx_track)
    registry.register("gpx_track_length", data_sources.gpx_track_length)
    registry.register("gpx_track_extent", data_sources.gpx_track_extent)
    registry.register("gpx_to_layer", data_sources.gpx_to_layer)
    registry.register("map_gpx_track", data_sources.map_gpx_track)
    registry.register("list_database_connections", data_sources.list_database_connections)
    registry.register("inspect_database_connection", data_sources.inspect_database_connection)
    registry.register("load_postgis_layer", data_sources.load_postgis_layer)
    registry.register("test_postgis_connection", data_sources.test_postgis_connection)
    registry.register("list_postgis_tables", data_sources.list_postgis_tables)
    registry.register("inspect_postgis_layer", data_sources.inspect_postgis_layer)
    registry.register("list_layer_tree", layer_tree.list_layer_tree)
    registry.register("list_duplicate_layers", layer_tree.list_duplicate_layers)
    registry.register("remove_layer", layer_tree.remove_layer)
    registry.register("remove_layers_by_name", layer_tree.remove_layers_by_name)
    registry.register("remove_layers_by_source_path", layer_tree.remove_layers_by_source_path)
    registry.register("clear_sigmai_temporary_layers", layer_tree.clear_sigmai_temporary_layers)
    registry.register("deduplicate_layers", layer_tree.deduplicate_layers)
    registry.register("create_clean_test_project", layer_tree.create_clean_test_project)
    registry.register("set_layer_visibility", layer_tree.set_layer_visibility)
    registry.register("move_layer_order", layer_tree.move_layer_order)
    registry.register("create_layer_group", layer_tree.create_layer_group)
    registry.register("move_layer_to_group", layer_tree.move_layer_to_group)
    registry.register("list_fields", attributes.list_fields)
    registry.register("sample_features", attributes.sample_features)
    registry.register("inspect_attribute_table", attributes.inspect_attribute_table)
    registry.register("field_statistics", attributes.field_statistics)
    registry.register("unique_values", attributes.unique_values)
    registry.register("validate_expression", expressions.validate_expression)
    registry.register("evaluate_expression", expressions.evaluate_expression)
    registry.register("query_features", expressions.query_features)
    registry.register("select_by_expression", selection.select_by_expression)
    registry.register("select_by_attribute", selection.select_by_attribute)
    registry.register("select_by_location", selection.select_by_location)
    registry.register("extract_by_expression", selection.extract_by_expression)
    registry.register("extract_by_attribute", selection.extract_by_attribute)
    registry.register("extract_by_location", selection.extract_by_location)
    registry.register("run_processing", run_processing.handle)
    registry.register("list_layouts", layouts.list_layouts)
    registry.register("create_layout", layouts.create_layout)
    registry.register("add_layout_map", cartography.add_layout_map)
    registry.register("set_layout_extent", cartography.set_layout_extent)
    registry.register("add_layout_label", cartography.add_layout_label)
    registry.register("add_layout_legend", cartography.add_layout_legend)
    registry.register("add_layout_scale_bar", cartography.add_layout_scale_bar)
    registry.register("add_layout_north_arrow", cartography.add_layout_north_arrow)
    registry.register("add_layout_grid", cartography.add_layout_grid)
    registry.register("add_layout_picture", cartography.add_layout_picture)
    registry.register("set_layer_style", cartography.set_layer_style)
    registry.register("apply_single_symbol", symbology.apply_single_symbol)
    registry.register("apply_categorized_style", symbology.apply_categorized_style)
    registry.register("apply_graduated_style", symbology.apply_graduated_style)
    registry.register("set_layer_opacity", symbology.set_layer_opacity)
    registry.register("inspect_layer_style", symbology.inspect_layer_style)
    registry.register("save_qml_style", symbology.save_qml_style)
    registry.register("load_qml_style", symbology.load_qml_style)
    registry.register("recommend_style_for_layer", symbology.recommend_style_for_layer)
    registry.register("create_labels", symbology.create_labels)
    registry.register("create_labels_from_expression", symbology.create_labels_from_expression)
    registry.register("enable_labels", symbology.enable_labels)
    registry.register("disable_labels", symbology.disable_labels)
    registry.register("generate_basic_map", cartography.generate_basic_map)
    registry.register("evaluate_layout_cartographic_completeness", cartography.evaluate_layout_cartographic_completeness_command)
    registry.register("generate_workflow_report", cartography.generate_workflow_report)
    registry.register("list_layout_templates", cartography.list_layout_templates)
    registry.register("choose_style_profile", cartography.choose_style_profile)
    registry.register("apply_cartographic_palette", cartography.apply_cartographic_palette)
    registry.register("apply_scientific_polygon_style", cartography.apply_cartographic_palette)
    registry.register("apply_scientific_line_style", cartography.apply_cartographic_palette)
    registry.register("apply_scientific_point_style", cartography.apply_cartographic_palette)
    registry.register("apply_boundary_highlight", cartography.apply_cartographic_palette)
    registry.register("create_map_hierarchy", cartography.suggest_layout_improvements)
    registry.register("validate_map_readability", cartography.validate_map_readability)
    registry.register("detect_visual_collisions", cartography.detect_visual_collisions)
    registry.register("suggest_layout_improvements", cartography.suggest_layout_improvements)
    registry.register("generate_professional_map", cartography.generate_professional_map)
    registry.register("evaluate_map_quality", cartography.evaluate_map_quality)
    registry.register("export_layout", export_layout.handle)
    registry.register("get_logs", get_logs.handle)
    registry.register("get_recent_errors", diagnostics.get_recent_errors)
    registry.register("list_installed_plugins", plugin_tools.list_installed_plugins)
    registry.register("list_qgis_plugins_extended", plugin_tools.list_qgis_plugins_extended)
    registry.register("inspect_plugin_capabilities", plugin_tools.inspect_plugin_capabilities)
    registry.register("list_plugin_processing_algorithms", plugin_tools.list_plugin_processing_algorithms)
    registry.register("get_plugin_algorithm_info", plugin_tools.get_plugin_algorithm_info)
    registry.register("build_plugin_capability_manifest", plugin_tools.build_plugin_capability_manifest)
    registry.register("dry_run_plugin_algorithm_generic", plugin_tools.dry_run_plugin_algorithm_generic)
    registry.register("run_plugin_algorithm_generic_safe", plugin_tools.run_plugin_algorithm_generic_safe)
    registry.register("run_plugin_algorithm_safe", plugin_tools.run_plugin_algorithm_safe)
    registry.register("generate_plugin_adapter_report", plugin_tools.generate_plugin_adapter_report)
    registry.register("search_qgis_plugin_repository", plugin_tools.search_qgis_plugin_repository)
    registry.register("download_qgis_plugin_zip", plugin_tools.download_qgis_plugin_zip)
    registry.register("inspect_qgis_plugin_zip", plugin_tools.inspect_qgis_plugin_zip)
    registry.register("install_plugin_from_zip", plugin_tools.install_plugin_from_zip)
    registry.register("install_qgis_plugin_from_repository", plugin_tools.install_qgis_plugin_from_repository)
    registry.register("list_processing_providers", processing_inventory.list_processing_providers)
    registry.register("list_processing_algorithms", processing_inventory.list_processing_algorithms)
    registry.register("get_processing_algorithm_info", processing_inventory.get_processing_algorithm_info)
    registry.register("recommend_qgis_tool", processing_inventory.recommend_qgis_tool)
    registry.register("inspect_plugin", plugin_tools.inspect_plugin)
    registry.register("validate_metadata_txt", plugin_tools.validate_metadata_txt)
    registry.register("check_plugin_structure", plugin_tools.check_plugin_structure)
    registry.register("check_plugin_imports", plugin_tools.check_plugin_imports)
    registry.register("check_plugin_resources", plugin_tools.check_plugin_resources)
    registry.register("check_plugin_icon", plugin_tools.check_plugin_icon)
    registry.register("check_plugin_runtime_status", plugin_tools.check_plugin_runtime_status)
    registry.register("check_plugin_menu_actions", plugin_tools.check_plugin_menu_actions)
    registry.register("check_plugin_toolbar_actions", plugin_tools.check_plugin_toolbar_actions)
    registry.register("check_processing_provider_registration", plugin_tools.check_processing_provider_registration)
    registry.register("check_plugin_algorithm_registration", plugin_tools.check_plugin_algorithm_registration)
    registry.register("collect_plugin_logs", plugin_tools.collect_plugin_logs)
    registry.register("generate_plugin_report", plugin_tools.generate_plugin_report)
    registry.register("package_plugin_zip", plugin_tools.package_plugin_zip)
    registry.register("install_plugin_from_folder", plugin_tools.install_plugin_from_folder)
    registry.register("update_plugin_from_folder", plugin_tools.update_plugin_from_folder)
    registry.register("enable_plugin", plugin_tools.enable_plugin)
    registry.register("disable_plugin", plugin_tools.disable_plugin)
    registry.register("reload_plugin", plugin_tools.reload_plugin)
    registry.register("uninstall_plugin", plugin_tools.uninstall_plugin)
    registry.register("self_inspect", plugin_tools.self_inspect)
    registry.register("self_health_check", plugin_tools.self_health_check)
    registry.register("self_backup", plugin_tools.self_backup)
    registry.register("self_validate_update", plugin_tools.self_validate_update)
    registry.register("self_stage_update", plugin_tools.self_stage_update)
    registry.register("self_apply_update", plugin_tools.self_apply_update)
    registry.register("self_restart_required", plugin_tools.self_restart_required)
    registry.register("self_rollback", plugin_tools.self_rollback)
    registry.register("self_generate_report", plugin_tools.self_generate_report)
    registry.register("evaluate_sigmai_maturity", platform.evaluate_sigmai_maturity)
    registry.register("get_dev_mode_status", dev_tools.dev_mode_status)
    registry.register("dev_execute_qgis_python", dev_tools.execute_qgis_python)
