from __future__ import annotations

from dataclasses import dataclass
from typing import Any


SCHEMA_VERSION = "0.2"

READ_ONLY = "read_only"
SAFE_WRITE = "safe_write"
PROJECT_WRITE = "project_write"
DEVELOPER = "developer"
PLUGIN_WRITE = "plugin_write"
DANGEROUS_PLUGIN_WRITE = "dangerous_plugin_write"
UNSAFE_DEVELOPER = "unsafe_developer"


@dataclass(frozen=True)
class CommandPermission:
    action: str
    group: str
    permission_level: str
    requires_confirmation: bool = False
    supports_dry_run: bool = False
    enabled: bool = True


COMMAND_PERMISSIONS: dict[str, CommandPermission] = {
    "status": CommandPermission("status", "system", READ_ONLY),
    "get_capabilities": CommandPermission("get_capabilities", "system", READ_ONLY),
    "get_qgis_environment": CommandPermission("get_qgis_environment", "system", READ_ONLY),
    "get_bridge_config": CommandPermission("get_bridge_config", "system", READ_ONLY),
    "get_logs": CommandPermission("get_logs", "system", READ_ONLY),
    "get_recent_errors": CommandPermission("get_recent_errors", "system", READ_ONLY),
    "get_project_info": CommandPermission("get_project_info", "project", READ_ONLY),
    "get_project_crs": CommandPermission("get_project_crs", "project", READ_ONLY),
    "list_project_layers": CommandPermission("list_project_layers", "project", READ_ONLY),
    "list_layouts": CommandPermission("list_layouts", "cartography", READ_ONLY),
    "list_layers": CommandPermission("list_layers", "layers", READ_ONLY),
    "get_layer_info": CommandPermission("get_layer_info", "layers", READ_ONLY),
    "load_vector_layer": CommandPermission("load_vector_layer", "layers", SAFE_WRITE, supports_dry_run=True),
    "export_layer": CommandPermission("export_layer", "layers", SAFE_WRITE, supports_dry_run=True),
    "load_raster_layer": CommandPermission("load_raster_layer", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_info": CommandPermission("raster_info", "raster", READ_ONLY),
    "raster_band_statistics": CommandPermission("raster_band_statistics", "raster", READ_ONLY),
    "raster_metadata_report": CommandPermission("raster_metadata_report", "raster", READ_ONLY),
    "raster_reproject": CommandPermission("raster_reproject", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_clip_by_extent": CommandPermission("raster_clip_by_extent", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_clip_by_mask": CommandPermission("raster_clip_by_mask", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_slope": CommandPermission("raster_slope", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_aspect": CommandPermission("raster_aspect", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_hillshade": CommandPermission("raster_hillshade", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_contours": CommandPermission("raster_contours", "raster", SAFE_WRITE, supports_dry_run=True),
    "raster_polygonize": CommandPermission("raster_polygonize", "raster", SAFE_WRITE, supports_dry_run=True),
    "get_user_profile": CommandPermission("get_user_profile", "user_profile", READ_ONLY),
    "set_user_profile": CommandPermission("set_user_profile", "user_profile", SAFE_WRITE, supports_dry_run=True),
    "clear_user_profile": CommandPermission("clear_user_profile", "user_profile", SAFE_WRITE, supports_dry_run=True),
    "plan_workflow": CommandPermission("plan_workflow", "workflows", READ_ONLY),
    "dry_run_workflow": CommandPermission("dry_run_workflow", "workflows", READ_ONLY),
    "execute_workflow": CommandPermission("execute_workflow", "workflows", SAFE_WRITE, supports_dry_run=True),
    "save_workflow_template": CommandPermission("save_workflow_template", "workflows", SAFE_WRITE, supports_dry_run=True),
    "list_workflow_templates": CommandPermission("list_workflow_templates", "workflows", READ_ONLY),
    "run_workflow_template": CommandPermission("run_workflow_template", "workflows", SAFE_WRITE, supports_dry_run=True),
    "start_job": CommandPermission("start_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "get_job_status": CommandPermission("get_job_status", "job_queue", READ_ONLY),
    "get_job_result": CommandPermission("get_job_result", "job_queue", READ_ONLY),
    "list_jobs": CommandPermission("list_jobs", "job_queue", READ_ONLY),
    "cancel_job": CommandPermission("cancel_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "job_logs": CommandPermission("job_logs", "job_queue", READ_ONLY),
    "clear_finished_jobs": CommandPermission("clear_finished_jobs", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "run_processing_job": CommandPermission("run_processing_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "run_workflow_job": CommandPermission("run_workflow_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "run_raster_job": CommandPermission("run_raster_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "run_map_export_job": CommandPermission("run_map_export_job", "job_queue", SAFE_WRITE, supports_dry_run=True),
    "create_atlas": CommandPermission("create_atlas", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "configure_atlas_coverage_layer": CommandPermission("configure_atlas_coverage_layer", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "set_atlas_filter_expression": CommandPermission("set_atlas_filter_expression", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "set_atlas_sort_expression": CommandPermission("set_atlas_sort_expression", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "export_atlas_pdf": CommandPermission("export_atlas_pdf", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "export_atlas_images": CommandPermission("export_atlas_images", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "generate_map_book": CommandPermission("generate_map_book", "atlas_reports", READ_ONLY),
    "create_report": CommandPermission("create_report", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "add_report_section": CommandPermission("add_report_section", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "export_report_pdf": CommandPermission("export_report_pdf", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "export_report_html": CommandPermission("export_report_html", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "generate_workflow_report_pdf": CommandPermission("generate_workflow_report_pdf", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "generate_analysis_report": CommandPermission("generate_analysis_report", "atlas_reports", SAFE_WRITE, supports_dry_run=True),
    "inspect_data_source": CommandPermission("inspect_data_source", "data_sources", READ_ONLY),
    "broken_data_source_report": CommandPermission("broken_data_source_report", "data_sources", READ_ONLY),
    "repair_data_source_path": CommandPermission("repair_data_source_path", "data_sources", SAFE_WRITE, supports_dry_run=True),
    "list_ogc_connections": CommandPermission("list_ogc_connections", "data_sources", READ_ONLY),
    "inspect_ogc_service": CommandPermission("inspect_ogc_service", "data_sources", READ_ONLY),
    "validate_service_url": CommandPermission("validate_service_url", "data_sources", READ_ONLY),
    "test_service_connection": CommandPermission("test_service_connection", "data_sources", READ_ONLY),
    "load_wms_layer": CommandPermission("load_wms_layer", "data_sources", SAFE_WRITE, supports_dry_run=True),
    "load_wfs_layer": CommandPermission("load_wfs_layer", "data_sources", SAFE_WRITE, supports_dry_run=True),
    "load_xyz_tile_layer": CommandPermission("load_xyz_tile_layer", "data_sources", SAFE_WRITE, supports_dry_run=True),
    "load_arcgis_rest_layer": CommandPermission("load_arcgis_rest_layer", "data_sources", SAFE_WRITE, supports_dry_run=True),
    "load_gpx": CommandPermission("load_gpx", "gps_gpx", SAFE_WRITE, supports_dry_run=True),
    "list_gpx_layers": CommandPermission("list_gpx_layers", "gps_gpx", READ_ONLY),
    "summarize_gpx_track": CommandPermission("summarize_gpx_track", "gps_gpx", READ_ONLY),
    "gpx_track_length": CommandPermission("gpx_track_length", "gps_gpx", READ_ONLY),
    "gpx_track_extent": CommandPermission("gpx_track_extent", "gps_gpx", READ_ONLY),
    "gpx_to_layer": CommandPermission("gpx_to_layer", "gps_gpx", SAFE_WRITE, supports_dry_run=True),
    "map_gpx_track": CommandPermission("map_gpx_track", "gps_gpx", SAFE_WRITE, supports_dry_run=True),
    "list_database_connections": CommandPermission("list_database_connections", "databases", READ_ONLY),
    "inspect_database_connection": CommandPermission("inspect_database_connection", "databases", READ_ONLY),
    "load_postgis_layer": CommandPermission("load_postgis_layer", "databases", SAFE_WRITE, supports_dry_run=True),
    "test_postgis_connection": CommandPermission("test_postgis_connection", "databases", READ_ONLY),
    "list_postgis_tables": CommandPermission("list_postgis_tables", "databases", READ_ONLY),
    "inspect_postgis_layer": CommandPermission("inspect_postgis_layer", "databases", READ_ONLY),
    "diagnose_crs": CommandPermission("diagnose_crs", "crs_quality", READ_ONLY),
    "validate_geometries": CommandPermission("validate_geometries", "crs_quality", READ_ONLY),
    "fix_geometries": CommandPermission("fix_geometries", "crs_quality", SAFE_WRITE, supports_dry_run=True),
    "run_processing": CommandPermission("run_processing", "processing", SAFE_WRITE, supports_dry_run=True),
    "buffer": CommandPermission("buffer", "vector_tools", SAFE_WRITE, supports_dry_run=True),
    "clip": CommandPermission("clip", "vector_tools", SAFE_WRITE, supports_dry_run=True),
    "dissolve": CommandPermission("dissolve", "vector_tools", SAFE_WRITE, supports_dry_run=True),
    "reproject_layer": CommandPermission("reproject_layer", "vector_tools", SAFE_WRITE, supports_dry_run=True),
    "intersection": CommandPermission("intersection", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "union": CommandPermission("union", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "difference": CommandPermission("difference", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "centroids": CommandPermission("centroids", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "multipart_to_singleparts": CommandPermission("multipart_to_singleparts", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "count_points_in_polygon": CommandPermission("count_points_in_polygon", "vector_analysis", SAFE_WRITE, supports_dry_run=True),
    "list_layer_tree": CommandPermission("list_layer_tree", "layer_tree", READ_ONLY),
    "list_duplicate_layers": CommandPermission("list_duplicate_layers", "layer_tree", READ_ONLY),
    "remove_layer": CommandPermission("remove_layer", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "remove_layers_by_name": CommandPermission("remove_layers_by_name", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "remove_layers_by_source_path": CommandPermission("remove_layers_by_source_path", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "clear_sigmai_temporary_layers": CommandPermission("clear_sigmai_temporary_layers", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "deduplicate_layers": CommandPermission("deduplicate_layers", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "create_clean_test_project": CommandPermission("create_clean_test_project", "layer_tree", SAFE_WRITE, requires_confirmation=True, supports_dry_run=True),
    "set_layer_visibility": CommandPermission("set_layer_visibility", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "move_layer_order": CommandPermission("move_layer_order", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "create_layer_group": CommandPermission("create_layer_group", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "move_layer_to_group": CommandPermission("move_layer_to_group", "layer_tree", SAFE_WRITE, supports_dry_run=True),
    "list_fields": CommandPermission("list_fields", "attribute_table", READ_ONLY),
    "sample_features": CommandPermission("sample_features", "attribute_table", READ_ONLY),
    "inspect_attribute_table": CommandPermission("inspect_attribute_table", "attribute_table", READ_ONLY),
    "field_statistics": CommandPermission("field_statistics", "attribute_table", READ_ONLY),
    "unique_values": CommandPermission("unique_values", "attribute_table", READ_ONLY),
    "validate_expression": CommandPermission("validate_expression", "expressions", READ_ONLY),
    "evaluate_expression": CommandPermission("evaluate_expression", "expressions", READ_ONLY),
    "query_features": CommandPermission("query_features", "expressions", READ_ONLY),
    "select_by_expression": CommandPermission("select_by_expression", "selection", SAFE_WRITE, supports_dry_run=True),
    "select_by_attribute": CommandPermission("select_by_attribute", "selection", SAFE_WRITE, supports_dry_run=True),
    "select_by_location": CommandPermission("select_by_location", "selection", SAFE_WRITE, supports_dry_run=True),
    "extract_by_expression": CommandPermission("extract_by_expression", "selection", SAFE_WRITE, supports_dry_run=True),
    "extract_by_attribute": CommandPermission("extract_by_attribute", "selection", SAFE_WRITE, supports_dry_run=True),
    "extract_by_location": CommandPermission("extract_by_location", "selection", SAFE_WRITE, supports_dry_run=True),
    "export_layout": CommandPermission("export_layout", "cartography", SAFE_WRITE, supports_dry_run=True),
    "create_layout": CommandPermission("create_layout", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_map": CommandPermission("add_layout_map", "cartography", SAFE_WRITE, supports_dry_run=True),
    "set_layout_extent": CommandPermission("set_layout_extent", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_label": CommandPermission("add_layout_label", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_legend": CommandPermission("add_layout_legend", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_scale_bar": CommandPermission("add_layout_scale_bar", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_north_arrow": CommandPermission("add_layout_north_arrow", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_grid": CommandPermission("add_layout_grid", "cartography", SAFE_WRITE, supports_dry_run=True),
    "add_layout_picture": CommandPermission("add_layout_picture", "cartography", SAFE_WRITE, supports_dry_run=True),
    "set_layer_style": CommandPermission("set_layer_style", "cartography", SAFE_WRITE, supports_dry_run=True),
    "generate_basic_map": CommandPermission("generate_basic_map", "cartography", SAFE_WRITE, supports_dry_run=True),
    "evaluate_layout_cartographic_completeness": CommandPermission("evaluate_layout_cartographic_completeness", "cartography", READ_ONLY),
    "generate_workflow_report": CommandPermission("generate_workflow_report", "cartography", SAFE_WRITE, supports_dry_run=True),
    "list_layout_templates": CommandPermission("list_layout_templates", "cartography", READ_ONLY),
    "generate_professional_map": CommandPermission("generate_professional_map", "cartography", SAFE_WRITE, supports_dry_run=True),
    "evaluate_map_quality": CommandPermission("evaluate_map_quality", "cartography", READ_ONLY),
    "choose_style_profile": CommandPermission("choose_style_profile", "cartographic_design", READ_ONLY),
    "apply_cartographic_palette": CommandPermission("apply_cartographic_palette", "cartographic_design", SAFE_WRITE, supports_dry_run=True),
    "apply_scientific_polygon_style": CommandPermission("apply_scientific_polygon_style", "cartographic_design", SAFE_WRITE, supports_dry_run=True),
    "apply_scientific_line_style": CommandPermission("apply_scientific_line_style", "cartographic_design", SAFE_WRITE, supports_dry_run=True),
    "apply_scientific_point_style": CommandPermission("apply_scientific_point_style", "cartographic_design", SAFE_WRITE, supports_dry_run=True),
    "apply_boundary_highlight": CommandPermission("apply_boundary_highlight", "cartographic_design", SAFE_WRITE, supports_dry_run=True),
    "create_map_hierarchy": CommandPermission("create_map_hierarchy", "cartographic_design", READ_ONLY),
    "validate_map_readability": CommandPermission("validate_map_readability", "cartographic_design", READ_ONLY),
    "detect_visual_collisions": CommandPermission("detect_visual_collisions", "cartographic_design", READ_ONLY),
    "suggest_layout_improvements": CommandPermission("suggest_layout_improvements", "cartographic_design", READ_ONLY),
    "list_processing_providers": CommandPermission("list_processing_providers", "processing_inventory", READ_ONLY),
    "list_processing_algorithms": CommandPermission("list_processing_algorithms", "processing_inventory", READ_ONLY),
    "get_processing_algorithm_info": CommandPermission("get_processing_algorithm_info", "processing_inventory", READ_ONLY),
    "recommend_qgis_tool": CommandPermission("recommend_qgis_tool", "processing_inventory", READ_ONLY),
    "list_qgis_plugins_extended": CommandPermission("list_qgis_plugins_extended", "plugin_orchestration", READ_ONLY),
    "inspect_plugin_capabilities": CommandPermission("inspect_plugin_capabilities", "plugin_orchestration", READ_ONLY),
    "list_plugin_processing_algorithms": CommandPermission("list_plugin_processing_algorithms", "plugin_orchestration", READ_ONLY),
    "get_plugin_algorithm_info": CommandPermission("get_plugin_algorithm_info", "plugin_orchestration", READ_ONLY),
    "build_plugin_capability_manifest": CommandPermission("build_plugin_capability_manifest", "plugin_orchestration", READ_ONLY),
    "dry_run_plugin_algorithm_generic": CommandPermission("dry_run_plugin_algorithm_generic", "plugin_orchestration", READ_ONLY),
    "run_plugin_algorithm_generic_safe": CommandPermission("run_plugin_algorithm_generic_safe", "plugin_orchestration", SAFE_WRITE, supports_dry_run=True),
    "run_plugin_algorithm_safe": CommandPermission("run_plugin_algorithm_safe", "plugin_orchestration", SAFE_WRITE, supports_dry_run=True),
    "generate_plugin_adapter_report": CommandPermission("generate_plugin_adapter_report", "plugin_orchestration", READ_ONLY),
    "search_qgis_plugin_repository": CommandPermission("search_qgis_plugin_repository", "plugin_management", READ_ONLY),
    "download_qgis_plugin_zip": CommandPermission("download_qgis_plugin_zip", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "inspect_qgis_plugin_zip": CommandPermission("inspect_qgis_plugin_zip", "plugin_management", READ_ONLY),
    "install_plugin_from_zip": CommandPermission("install_plugin_from_zip", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "install_qgis_plugin_from_repository": CommandPermission("install_qgis_plugin_from_repository", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "apply_single_symbol": CommandPermission("apply_single_symbol", "symbology", SAFE_WRITE, supports_dry_run=True),
    "apply_categorized_style": CommandPermission("apply_categorized_style", "symbology", SAFE_WRITE, supports_dry_run=True),
    "apply_graduated_style": CommandPermission("apply_graduated_style", "symbology", SAFE_WRITE, supports_dry_run=True),
    "set_layer_opacity": CommandPermission("set_layer_opacity", "symbology", SAFE_WRITE, supports_dry_run=True),
    "inspect_layer_style": CommandPermission("inspect_layer_style", "symbology", READ_ONLY),
    "save_qml_style": CommandPermission("save_qml_style", "symbology", SAFE_WRITE, supports_dry_run=True),
    "load_qml_style": CommandPermission("load_qml_style", "symbology", SAFE_WRITE, supports_dry_run=True),
    "recommend_style_for_layer": CommandPermission("recommend_style_for_layer", "symbology", READ_ONLY),
    "create_labels": CommandPermission("create_labels", "labels", SAFE_WRITE, supports_dry_run=True),
    "create_labels_from_expression": CommandPermission("create_labels_from_expression", "labels", SAFE_WRITE, supports_dry_run=True),
    "enable_labels": CommandPermission("enable_labels", "labels", SAFE_WRITE, supports_dry_run=True),
    "disable_labels": CommandPermission("disable_labels", "labels", SAFE_WRITE, supports_dry_run=True),
    "list_installed_plugins": CommandPermission("list_installed_plugins", "plugin_management", READ_ONLY),
    "inspect_plugin": CommandPermission("inspect_plugin", "plugin_management", READ_ONLY),
    "validate_metadata_txt": CommandPermission("validate_metadata_txt", "plugin_management", READ_ONLY),
    "check_plugin_imports": CommandPermission("check_plugin_imports", "plugin_management", READ_ONLY),
    "check_plugin_structure": CommandPermission("check_plugin_structure", "plugin_management", READ_ONLY),
    "check_plugin_resources": CommandPermission("check_plugin_resources", "plugin_management", READ_ONLY),
    "check_plugin_icon": CommandPermission("check_plugin_icon", "plugin_management", READ_ONLY),
    "check_plugin_runtime_status": CommandPermission("check_plugin_runtime_status", "plugin_management", READ_ONLY),
    "check_plugin_menu_actions": CommandPermission("check_plugin_menu_actions", "plugin_management", DEVELOPER),
    "check_plugin_toolbar_actions": CommandPermission("check_plugin_toolbar_actions", "plugin_management", DEVELOPER),
    "check_processing_provider_registration": CommandPermission("check_processing_provider_registration", "plugin_management", DEVELOPER),
    "check_plugin_algorithm_registration": CommandPermission("check_plugin_algorithm_registration", "plugin_management", DEVELOPER),
    "collect_plugin_logs": CommandPermission("collect_plugin_logs", "plugin_management", READ_ONLY),
    "generate_plugin_report": CommandPermission("generate_plugin_report", "plugin_management", READ_ONLY, supports_dry_run=True),
    "package_plugin_zip": CommandPermission("package_plugin_zip", "plugin_management", DEVELOPER, supports_dry_run=True),
    "install_plugin_from_folder": CommandPermission("install_plugin_from_folder", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "update_plugin_from_folder": CommandPermission("update_plugin_from_folder", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "enable_plugin": CommandPermission("enable_plugin", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "disable_plugin": CommandPermission("disable_plugin", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "reload_plugin": CommandPermission("reload_plugin", "plugin_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "uninstall_plugin": CommandPermission("uninstall_plugin", "plugin_management", DANGEROUS_PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "self_inspect": CommandPermission("self_inspect", "self_management", READ_ONLY),
    "self_health_check": CommandPermission("self_health_check", "self_management", READ_ONLY),
    "self_generate_report": CommandPermission("self_generate_report", "self_management", READ_ONLY, supports_dry_run=True),
    "self_backup": CommandPermission("self_backup", "self_management", READ_ONLY, supports_dry_run=True),
    "self_validate_update": CommandPermission("self_validate_update", "self_management", READ_ONLY, supports_dry_run=True),
    "self_stage_update": CommandPermission("self_stage_update", "self_management", PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "self_apply_update": CommandPermission("self_apply_update", "self_management", DANGEROUS_PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "self_restart_required": CommandPermission("self_restart_required", "self_management", READ_ONLY),
    "self_rollback": CommandPermission("self_rollback", "self_management", DANGEROUS_PLUGIN_WRITE, requires_confirmation=True, supports_dry_run=True),
    "evaluate_sigmai_maturity": CommandPermission("evaluate_sigmai_maturity", "platform_maturity", READ_ONLY),
    "get_dev_mode_status": CommandPermission("get_dev_mode_status", "developer_mode", READ_ONLY),
    "dev_execute_qgis_python": CommandPermission("dev_execute_qgis_python", "developer_mode", UNSAFE_DEVELOPER, requires_confirmation=True, supports_dry_run=True, enabled=True),
}


def allowed_actions() -> set[str]:
    return {action for action, metadata in COMMAND_PERMISSIONS.items() if metadata.enabled}


def permission_for(action: str) -> CommandPermission | None:
    return COMMAND_PERMISSIONS.get(action)


def capabilities_payload(developer_mode: bool = False) -> dict[str, Any]:
    groups: dict[str, list[str]] = {}
    requires_confirmation: list[str] = []
    dry_run_supported: list[str] = []
    disabled_actions: list[str] = []

    for action, metadata in sorted(COMMAND_PERMISSIONS.items()):
        if metadata.enabled:
            groups.setdefault(metadata.group, []).append(action)
        else:
            disabled_actions.append(action)
        if metadata.requires_confirmation:
            requires_confirmation.append(action)
        if metadata.supports_dry_run:
            dry_run_supported.append(action)

    return {
        "schema_version": SCHEMA_VERSION,
        "display_name": "SIGMAI",
        "subtitle": "Secure GIS-AI Interface",
        "author": "MACIEL, L. S. C.",
        "author_email": "herpetomantiqueira@gmail.com",
        "associated_project": "Herpeto Mantiqueira",
        "groups": groups,
        "commands": {
            action: {
                "group": metadata.group,
                "permission_level": metadata.permission_level,
                "supports_dry_run": metadata.supports_dry_run,
                "requires_confirmation": metadata.requires_confirmation,
                "enabled": metadata.enabled,
            }
            for action, metadata in sorted(COMMAND_PERMISSIONS.items())
        },
        "dangerous_actions": [],
        "requires_confirmation": requires_confirmation,
        "dry_run_supported": dry_run_supported,
        "disabled_actions": disabled_actions,
        "permission_levels": [READ_ONLY, SAFE_WRITE, PROJECT_WRITE, DEVELOPER, PLUGIN_WRITE, DANGEROUS_PLUGIN_WRITE, UNSAFE_DEVELOPER],
        "default_permission_level": READ_ONLY,
        "developer_mode": developer_mode,
        "unsafe_developer_mode": False,
        "developer_mode_controls": {
            "status_command": "get_dev_mode_status",
            "python_execution_command": "dev_execute_qgis_python",
            "ui_required_to_enable": True,
            "confirmation_phrase": "SIM",
            "default_enabled": False,
            "warning": "DEV mode allows explicit QGIS Python execution and can corrupt the active QGIS session or project.",
        },
        "maturity_level": {
            "level": 14,
            "label": "Broad QGIS Ecosystem Coverage Roadmap Capable",
            "requires_real_qgis_validation": True,
        },
        "supported_formats": {
            "layout_export": ["pdf", "png"],
            "vector_export": ["GPKG", "GeoJSON", "ESRI Shapefile"],
            "raster_input": ["GeoTIFF", "VRT", "ASC", "IMG", "JP2"],
            "raster_output": ["GeoTIFF", "TEMPORARY_OUTPUT"],
            "picture_items": ["png", "jpg", "jpeg", "svg"],
        },
        "cartography_capabilities": {
            "atomic_layout_commands": [
                "create_layout",
                "add_layout_map",
                "set_layout_extent",
                "set_layer_style",
                "add_layout_label",
                "add_layout_legend",
                "add_layout_scale_bar",
                "add_layout_north_arrow",
                "add_layout_grid",
                "add_layout_picture",
                "export_layout",
                "evaluate_layout_cartographic_completeness",
            ],
            "orchestrators": ["generate_basic_map", "generate_professional_map", "generate_workflow_report"],
            "blank_map_protection": ["add_layout_map", "set_layout_extent", "set_layer_style", "evaluate_layout_cartographic_completeness"],
            "professional_templates": ["scientific_basic", "scientific_publication", "environmental_report", "minimal_clean", "technical_dark", "atlas_page"],
        },
        "vector_capabilities": ["diagnose_crs", "validate_geometries", "fix_geometries", "buffer", "clip", "dissolve", "reproject_layer", "export_layer", "intersection", "union", "difference", "centroids", "multipart_to_singleparts", "count_points_in_polygon"],
        "raster_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "raster"],
        "user_profile_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "user_profile"],
        "attribute_capabilities": ["list_fields", "sample_features", "inspect_attribute_table", "field_statistics", "unique_values"],
        "expression_capabilities": ["validate_expression", "evaluate_expression", "query_features"],
        "selection_capabilities": ["select_by_expression", "select_by_attribute", "select_by_location", "extract_by_expression", "extract_by_attribute", "extract_by_location"],
        "layer_tree_capabilities": ["list_layer_tree", "set_layer_visibility", "move_layer_order", "create_layer_group", "move_layer_to_group"],
        "symbology_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "symbology"],
        "label_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "labels"],
        "cartographic_design_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "cartographic_design"],
        "processing_inventory_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "processing_inventory"],
        "plugin_orchestration_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "plugin_orchestration"],
        "workflow_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "workflows"] + ["generate_workflow_report"],
        "job_queue_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "job_queue"],
        "atlas_report_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "atlas_reports"],
        "data_source_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "data_sources"],
        "gps_gpx_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "gps_gpx"],
        "database_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "databases"],
        "plugin_management_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "plugin_management"],
        "self_management_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "self_management"],
        "platform_maturity_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "platform_maturity"],
        "developer_mode_capabilities": [action for action, metadata in sorted(COMMAND_PERMISSIONS.items()) if metadata.group == "developer_mode"],
        "mcp_capabilities": [
            "dependency_free_json_lines_transport",
            "tool_manifest",
            "session_discovery",
            "token_masking",
            "read_only_tools",
            "dry_run_tools",
            "dangerous_action_blocking",
            "sigmai_session_discovery",
        ],
        "limitations": [
            "Raster core is implemented through explicit wrappers and Processing allowlist; advanced raster calculator, reclassification and zonal statistics remain planned.",
            "OGC/database source commands and advanced expression/editing commands are planned next phases.",
            "The initial job queue runs read-only actions and dry-run mutations; real long-running QGIS mutations require the future QgsTask-safe runner.",
            "QGIS must load the updated plugin package before new runtime capabilities appear in live get_capabilities.",
        ],
    }
