"""Textos da interface do SIGMAI — Deutsch (de).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Sichere GIS-KI-Schnittstelle",
    "subtitle": "Sichere GIS-KI-Schnittstelle",
    "context": "Lokale Brücke zwischen KI-Assistenten und QGIS",
    "online": "Verbunden",
    "offline": "Gestoppt",
    # abas
    "tab_connection": "Verbindung",
    "tab_access": "Zugriff",
    "tab_activity": "Aktivität",
    "tab_advanced": "Erweitert",
    "tab_help": "Hilfe",
    # aba Conexão
    "step1_title": "Starten Sie die Brücke zu QGIS",
    "step1_hint": "Die Brücke lauscht nur auf 127.0.0.1 und verlangt ein Token. Nichts verlässt Ihren Rechner.",
    "step1_start": "Brücke starten",
    "step1_stop": "Brücke stoppen",
    "step1_running": "Brücke aktiv auf {host}:{port} · QGIS {qgis}",
    "step1_stopped": "Die Brücke ist gestoppt. Klicken Sie auf „Brücke starten“.",
    "step2_title": "Richten Sie Ihren KI-Assistenten ein",
    "step2_hint": "Wählen Sie das Programm, das Sie verwenden. SIGMAI erstellt die Konfiguration mit den richtigen Pfaden.",
    "step2_client": "Programm",
    "step2_where": "Wo einfügen",
    "step2_copy": "Konfiguration kopieren",
    "step2_open_folder": "Konfigurationsordner öffnen",
    "step2_copied": "Konfiguration kopiert. Fügen Sie sie in die angegebene Datei ein und starten Sie das Programm neu.",
    "step3_title": "Prüfen Sie, ob es funktioniert",
    "step3_hint": "Der Test durchläuft die Brücke von Anfang bis Ende, so wie ein KI-Assistent es täte.",
    "step3_run": "Verbindung testen",
    "step3_running": "Test läuft…",
    "step3_never": "Noch nicht getestet.",
    # aba Acesso
    "access_title": "Was die KI in diesem QGIS tun darf",
    "access_hint": "Lesebefehle und Simulationen funktionieren immer. Diese Wahl gilt für Aktionen, die das Projekt verändern oder Dateien schreiben.",
    "mode_read_only": "Nur lesen",
    "mode_read_only_hint": "Die KI untersucht und simuliert; nichts wird verändert oder geschrieben. Empfohlen für den Anfang.",
    "mode_ask": "Immer fragen",
    "mode_ask_hint": "Jede verändernde Aktion öffnet eine Bestätigung, die genau zeigt, was geschehen wird.",
    "mode_allow": "Für diese Sitzung erlauben",
    "mode_allow_hint": "Die KI handelt ohne Rückfrage, innerhalb der unten festgelegten Ordner und Grenzen.",
    "folders_title": "Ordner, in die die KI schreiben darf",
    "folders_hint": "Leer bedeutet: jeder Ordner. Eine Einschränkung ist der wirksamste Schutz gegen Schreiben am falschen Ort.",
    "folders_add": "Ordner hinzufügen…",
    "folders_remove": "Entfernen",
    "limits_title": "Grenzen dieser Sitzung",
    "limits_hint": "Eine Obergrenze pro Sitzung verhindert, dass eine Schleife des Assistenten Hunderte Dateien erzeugt.",
    "limit_writes": "Änderungen am Projekt",
    "limit_exports": "Karten und Exporte",
    "limit_processing": "Processing-Läufe",
    "limits_reset": "Zähler und Freigaben zurücksetzen",
    # aba Atividade
    "activity_title": "Was die KI angefragt hat",
    "activity_hint": "Protokoll der Zugriffsentscheidungen dieser Sitzung. Kein Token erscheint hier.",
    "activity_refresh": "Aktualisieren",
    "activity_export": "Bericht exportieren…",
    "activity_empty": "Noch keine Anfragen.",
    "col_time": "Wann",
    "col_event": "Entscheidung",
    "col_action": "Befehl",
    "col_detail": "Detail",
    # aba Avançado
    "advanced_endpoint": "Lokale Brücke",
    "advanced_host": "Host",
    "advanced_port": "Port",
    "advanced_token": "Token",
    "advanced_show": "Anzeigen",
    "advanced_hide": "Verbergen",
    "advanced_copy_token": "Kopieren",
    "advanced_regenerate": "Neues Token erzeugen",
    "advanced_session_file": "Sitzungsdatei",
    "advanced_open_logs": "Diagnoseordner öffnen",
    "advanced_autostart": "Brücke zusammen mit QGIS starten",
    "advanced_write_session": "Sitzungsdatei schreiben, damit KI-Clients die Brücke finden",
    "advanced_persist_token": "Dasselbe Token über QGIS-Sitzungen hinweg behalten",
    "advanced_persist_hint": "Aus (Standard): Das Token ändert sich bei jedem Start von QGIS, und in Schritt 2 eingerichtete Clients lesen das neue Token aus der Sitzungsdatei, ohne dass etwas neu gemacht werden muss. Nur einschalten, wenn Sie das Token irgendwo von Hand eingefügt haben.",
    "advanced_token_warning": "Behandeln Sie das Token wie ein Passwort. Wer es besitzt, kann dieses QGIS über die lokale Brücke steuern.",
    # Modo DEV
    "dev_title": "Entwicklermodus",
    "dev_hint": "Erlaubt die Ausführung von Python in QGIS für die Plugin-Entwicklung. Standardmäßig aus.",
    "dev_warning": "Dieser Modus kann Ihr QGIS beschädigen: Er führt Code direkt im Interpreter der Anwendung aus.",
    "dev_off": "Aus",
    "dev_on": "EIN",
    "dev_enable": "DEV-Modus aktivieren",
    "dev_disable": "DEV-Modus deaktivieren",
    "dev_dialog_title": "SIGMAI-DEV-Modus aktivieren",
    "dev_dialog_prompt": "Geben Sie YES ein, um zu bestätigen:",
    # aba Ajuda
    "help_title": "So funktioniert SIGMAI",
    "help_what_title": "Was ist das",
    "help_what": "SIGMAI öffnet eine Tür zwischen QGIS und einem KI-Assistenten. Sie sprechen mit dem Assistenten in Ihrer Sprache; er bedient QGIS für Sie und liefert die fertige Karte zurück. Sie müssen weder wissen, wo die QGIS-Menüs sind, noch was Maßstab, Projektion oder Legende bedeuten — SIGMAI kümmert sich darum und erzählt, was es getan hat.",
    "help_try_title": "Sätze für den Anfang",
    "help_try": "• „Welche Layer sind in diesem Projekt geöffnet?“\n• „Mach eine Karte des Wanderwegs auf A4, zum Drucken.“\n• „Karte des Parks mit den umliegenden Gemeinden und einer kleinen Übersichtskarte.“\n• „Setz die Namen der Einheiten auf die Karte.“\n• „Zwei Karten auf einem Blatt: der Park und der ganze Bundesstaat.“\n• „Ist diese Karte gut genug zum Veröffentlichen? Was fehlt ihr?“",
    "help_ask_title": "Zwei Dinge, die der Assistent fragen wird",
    "help_ask": "Woher die Daten stammen und wer die Karte verantwortet. Ohne diese beiden Angaben kann die Karte in keiner Arbeit zitiert werden, und SIGMAI verweigert die Bestnote. Die Urheberschaft der Karte liegt bei Ihnen (oder bei der Person, die sie erstellt hat) — nicht bei diesem Plugin.",
    "help_quality_title": "Die Kartennote",
    "help_quality": "Jede erzeugte Karte erhält eine Note von A bis E, mit der Liste dessen, was falsch ist, und was jeden Punkt behebt. Die Note ist keine Meinung: Sie ist ein Regelwerk aus expliziten Regeln, jede mit ihrem Grund. Bitten Sie den Assistenten: „Erkläre mir die Note dieser Karte.“",
    "help_refuse_title": "Wenn SIGMAI ablehnt",
    "help_refuse": "Ablehnen ist Absicht. Fordert der Assistent ein Seitenformat, das es nicht gibt, ein leeres Beschriftungsfeld oder einen Ordner anstelle einer Datei, hält SIGMAI an und sagt, was es akzeptiert — statt stillschweigend eine andere Karte zu liefern als die bestellte.",
    "help_privacy_title": "Wo Ihre Daten bleiben",
    "help_privacy": "Die Brücke lauscht nur auf 127.0.0.1, also auf Ihrem eigenen Rechner, und verlangt ein Token. Ihre Dateien werden nirgendwohin gesendet: Der Assistent schickt Befehle, QGIS führt sie hier aus und gibt das Ergebnis zurück.",
    "help_docs": "Dokumentation und Code: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "Über SIGMAI",
    "about_plugin": "Plugin-Autor: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · MIT-Lizenz · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "Die Urheberschaft des Plugins ist nicht die der Karten: Geben Sie map_author und data_source für jede erzeugte Karte an.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "Der KI-Assistent möchte eine Aktion ausführen",
    "consent_allow": "Einmal erlauben",
    "consent_allow_category": "Diese ganze Kategorie für diese Sitzung erlauben",
    "consent_deny": "Ablehnen",
    "msg_started": "SIGMAI-Brücke gestartet auf {host}:{port}.",
    "msg_stopped": "SIGMAI-Brücke gestoppt.",
    "msg_start_failed": "Die SIGMAI-Brücke konnte nicht gestartet werden",
    # idioma e aparência
    "language_label": "Sprache der Oberfläche",
    "theme_label": "Erscheinungsbild",
    "theme_auto": "Automatisch (folgt dem QGIS-Thema)",
    "theme_light": "Hell",
    "theme_dark": "Dunkel",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Erlaubt",
    "event_denied_read_only": "Blockiert (nur lesen)",
    "event_denied_by_user": "Von Ihnen abgelehnt",
    "event_denied_remembered": "Abgelehnt (Kategorie zuvor verweigert)",
    "event_denied_limit": "Blockiert (Sitzungsgrenze)",
    "event_denied_output_root": "Blockiert (Ordner nicht erlaubt)",
    "event_denied_never_auto": "Blockiert (erfordert Ihre Aktion im Panel)",
    "event_denied_no_prompt": "Blockiert (Panel nicht verfügbar)",
    "event_prompt_failed": "Bestätigung fehlgeschlagen",
    "event_mode_changed": "Zugriffsmodus geändert",
    "event_limit_changed": "Grenze geändert",
    "event_output_roots_changed": "Erlaubte Ordner geändert",
    "event_session_reset": "Sitzung zurückgesetzt",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Kartographie",
    "category_simbologia": "Symbologie",
    "category_camadas": "Layer",
    "category_raster": "Raster",
    "category_vetor": "Vektor",
    "category_selecao": "Auswahl",
    "category_processing": "Processing",
    "category_fluxos": "Workflows",
    "category_atlas": "Atlas und Berichte",
    "category_fontes": "Datenquellen",
    "category_bancos": "Datenbanken",
    "category_geometria": "Geometrie",
    "category_expressoes": "Ausdrücke",
    "category_perfil": "Profil",
    "category_gps": "GPS",
    "category_projeto": "Projekt",
    "category_desc_cartography": "Layouts anlegen, Karten zusammenstellen und exportieren",
    "category_desc_cartographic_design": "Kartographische Stile und Paletten anwenden",
    "category_desc_symbology": "Symbole, Farben und Beschriftungen der Layer ändern",
    "category_desc_layers": "Layer laden und exportieren",
    "category_desc_layer_tree": "Layer des Projekts umordnen, gruppieren und entfernen",
    "category_desc_raster": "Raster verarbeiten und abgeleitete Dateien schreiben",
    "category_desc_vector": "Geometrische Operationen, die neue Layer erzeugen",
    "category_desc_selection": "Objekte auswählen und extrahieren",
    "category_desc_processing": "QGIS-Processing-Algorithmen ausführen",
    "category_desc_workflows": "Zusammengesetzte Workflows ausführen",
    "category_desc_atlas_reports": "Atlanten, Serien und Berichte erzeugen",
    "category_desc_data_sources": "Mit Diensten verbinden und Pfade reparieren",
    "category_desc_databases": "Mit Datenbanken verbinden und Tabellen laden",
    "category_desc_crs_quality": "Ungültige Geometrien korrigieren",
    "category_desc_expressions": "QGIS-Ausdrücke auswerten",
    "category_desc_user_profile": "Das Urheberprofil des Benutzers speichern",
    "category_desc_gps_gpx": "GPX-Tracks laden und umwandeln",
    "category_desc_project": "Die letzte Aktion des Assistenten im Projekt rückgängig machen",
    "category_desc_default": "Aktion, die das Projekt verändert oder Dateien schreibt",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Aktion",
    "consent_category": "Kategorie",
    "consent_writes_to": "Schreibt nach",
    "consent_params": "Parameter",
    # autoteste (passo 3)
    "selftest_bridge": "Lokale Brücke",
    "selftest_auth": "Authentifizierung",
    "selftest_project": "QGIS-Projekt",
    "selftest_session": "Sitzungsdatei",
    "selftest_mcp": "MCP-Server",
    "selftest_mode": "Zugriffsmodus",
    "selftest_bridge_off": "Die Brücke ist gestoppt. Starten Sie sie in Schritt 1.",
    "selftest_bridge_ok": "antwortet auf {host}:{port} (Plugin {version})",
    "selftest_bridge_fail": "keine Antwort: {error}",
    "selftest_auth_leak": "die Brücke hat eine Anfrage OHNE Token angenommen — das darf nie passieren",
    "selftest_auth_ok": "eine Anfrage ohne Token wird wie erwartet abgelehnt",
    "selftest_auth_http": "unerwartete HTTP-Antwort {code}",
    "selftest_project_ok": "{count} Layer, KBS {crs}",
    "selftest_crs_undefined": "nicht festgelegt",
    "selftest_session_disabled": "unter „Erweitert“ ausgeschaltet; KI-Clients finden die Brücke nicht von selbst",
    "selftest_session_missing": "nicht gefunden unter {path}",
    "selftest_session_unreadable": "nicht lesbar: {error}",
    "selftest_session_port": "zeigt auf Port {file_port}, aber die Brücke läuft auf {port}",
    "selftest_session_ok": "geschrieben und stimmig mit der Brücke",
    "selftest_mcp_missing": "Datei fehlt: {path}",
    "selftest_mcp_no_python": "Interpreter nicht gefunden: {executable}",
    "selftest_mcp_ok": "{server} hat geantwortet und die Brücke erreicht, gestartet wie der KI-Client es tun wird: {python}",
    "selftest_mcp_failed": "Der KI-Client kann SIGMAI mit {python} nicht verwenden (Schritt {stage}): {error}",
    "selftest_mode_read_only": "nur lesen: Die KI kann untersuchen und simulieren, aber keine Karten erzeugen. Ändern Sie es jederzeit im Reiter „Zugriff“.",
    # clientes de IA (passo 2)
    "client_generic_label": "Anderer MCP-Client",
    "client_path_claude_code": ".mcp.json im Projektstamm, oder ~/.claude.json",
    "client_path_generic": "siehe die Dokumentation des Clients",
    "client_note_claude_desktop": "Menü Claude → Settings… → Reiter Developer → Edit Config. Nach dem Speichern Claude Desktop vollständig beenden und neu öffnen.",
    "client_note_claude_code": "Oder führen Sie den folgenden Befehl im Terminal innerhalb des Projekts aus.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, oder bearbeiten Sie die Datei direkt.",
    "client_note_codex": "Hängen Sie den Block an das Ende der Konfigurationsdatei an.",
    "client_note_generic": "Jeder Client, der MCP über stdio spricht, funktioniert. Der Vertrag: den folgenden Befehl als Unterprozess starten und zeilenweise getrenntes JSON-RPC 2.0 austauschen.",
}
