"""Textos da interface do SIGMAI — English (en).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Secure GIS-AI Interface",
    "subtitle": "Secure GIS-AI Interface",
    "context": "Local bridge between AI assistants and QGIS",
    "online": "Connected",
    "offline": "Stopped",
    # abas
    "tab_connection": "Connection",
    "tab_access": "Access",
    "tab_activity": "Activity",
    "tab_advanced": "Advanced",
    "tab_help": "Help",
    # aba Conexão
    "step1_title": "Start the bridge to QGIS",
    "step1_hint": "The bridge listens on 127.0.0.1 only and requires a token. Nothing leaves your machine.",
    "step1_start": "Start bridge",
    "step1_stop": "Stop bridge",
    "step1_running": "Bridge running on {host}:{port} · QGIS {qgis}",
    "step1_stopped": "The bridge is stopped. Click Start bridge.",
    "step2_title": "Configure your AI assistant",
    "step2_hint": "Pick the program you use. SIGMAI fills in the correct paths for you.",
    "step2_client": "Program",
    "step2_where": "Where to paste it",
    "step2_copy": "Copy configuration",
    "step2_open_folder": "Open configuration folder",
    "step2_copied": "Configuration copied. Paste it into the file above and restart the program.",
    "step3_title": "Check that it works",
    "step3_hint": "The check walks the whole bridge, the way an AI assistant would.",
    "step3_run": "Test connection",
    "step3_running": "Testing…",
    "step3_never": "Not tested yet.",
    # aba Acesso
    "access_title": "What the AI may do in this QGIS project",
    "access_hint": "Read commands and dry runs always work. This choice governs actions that change the project or write files.",
    "mode_read_only": "Read only",
    "mode_read_only_hint": "The AI inspects and simulates; nothing is changed or written. Recommended when you are getting started.",
    "mode_ask": "Ask every time",
    "mode_ask_hint": "Every changing action opens a confirmation showing exactly what will happen.",
    "mode_allow": "Allow for this session",
    "mode_allow_hint": "The AI acts without asking, within the folders and limits set below.",
    "folders_title": "Folders the AI may write to",
    "folders_hint": "Empty means any folder. Restricting this is the most effective guard against writing to the wrong place.",
    "folders_add": "Add folder…",
    "folders_remove": "Remove",
    "limits_title": "Limits for this session",
    "limits_hint": "A per-session ceiling stops an assistant loop from producing hundreds of files.",
    "limit_writes": "Project changes",
    "limit_exports": "Maps and exports",
    "limit_processing": "Processing runs",
    "limits_reset": "Reset counters and approvals",
    # aba Atividade
    "activity_title": "What the AI asked for",
    "activity_hint": "Access decisions recorded this session. No token ever appears here.",
    "activity_refresh": "Refresh",
    "activity_export": "Export report…",
    "activity_empty": "No requests yet.",
    "col_time": "When",
    "col_event": "Decision",
    "col_action": "Command",
    "col_detail": "Detail",
    # aba Avançado
    "advanced_endpoint": "Local bridge",
    "advanced_host": "Host",
    "advanced_port": "Port",
    "advanced_access_key": "Token",
    "advanced_show": "Show",
    "advanced_hide": "Hide",
    "advanced_copy_access_key": "Copy",
    "advanced_regenerate": "Generate a new token",
    "advanced_session_file": "Session file",
    "advanced_open_logs": "Open diagnostics folder",
    "advanced_autostart": "Start the bridge together with QGIS",
    "advanced_write_session": "Write the session file so AI clients can find the bridge",
    "advanced_persist_access_key": "Keep the same token across QGIS sessions",
    "advanced_persist_hint": "Off (the default), the token changes every time QGIS starts, and clients set up in step 2 read the new token from the session file with nothing to redo. Turn it on only if you pasted the token somewhere by hand.",
    "advanced_access_key_warning": "Treat the token as a password. Anyone holding it can control this QGIS instance through the local bridge.",
    # Modo DEV
    "dev_title": "Developer Mode",
    "dev_hint": "Enables Python execution inside QGIS for plugin development. Off by default.",
    "dev_warning": "This mode can corrupt your QGIS: it runs code directly in the application interpreter.",
    "dev_off": "Off",
    "dev_on": "ON",
    "dev_enable": "Enable DEV mode",
    "dev_disable": "Disable DEV mode",
    "dev_dialog_title": "Enable SIGMAI DEV mode",
    "dev_dialog_prompt": "Type YES to confirm:",
    # aba Ajuda
    "help_title": "How SIGMAI works",
    "help_what_title": "What this is",
    "help_what": "SIGMAI opens a channel between QGIS and an AI assistant. You talk to the assistant in plain language; it drives QGIS for you and hands back the finished map. You do not need to know where the QGIS menus are, nor what scale, projection or legend mean — SIGMAI handles that and tells you what it did.",
    "help_try_title": "Sentences to start with",
    "help_try": "• “What layers are open in this project?”\n• “Make a map of the trail on A4, for printing.”\n• “Map of the park showing the surrounding municipalities, with a locator inset.”\n• “Put the names of the units on the map.”\n• “Two maps on one sheet: the park and the whole state.”\n• “Is this map good enough to publish? What is missing?”",
    "help_ask_title": "Two things the assistant will ask you",
    "help_ask": "Where the data came from and who signs the map. Without those two, the map cannot be cited in a paper, and SIGMAI will not give it a top grade. Map authorship is yours (or whoever made it) — it is not the authorship of this plugin.",
    "help_quality_title": "The map grade",
    "help_quality": "Every map is graded A to E, with the list of what is wrong and what fixes each item. The grade is not an opinion: it is an explicit rulebook, each rule carrying the reason it exists. Ask the assistant to “explain this map's grade”.",
    "help_refuse_title": "When SIGMAI refuses",
    "help_refuse": "Refusing is deliberate. If the assistant asks for a page size that does not exist, an empty label field or a folder where a file belongs, SIGMAI stops and says what it accepts — instead of quietly handing over a different map from the one requested.",
    "help_privacy_title": "Where your data stays",
    "help_privacy": "The bridge listens on 127.0.0.1 only — your own machine — and requires a token. Your files are not uploaded anywhere: the assistant sends commands, QGIS runs them here and returns the result.",
    "help_docs": "Documentation and code: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "About SIGMAI",
    "about_plugin": "Plugin author: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · MIT License · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "Plugin authorship is not map authorship: set map_author and data_source on every map you generate.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "The AI assistant wants to run an action",
    "consent_allow": "Allow once",
    "consent_allow_category": "Allow this whole category for this session",
    "consent_deny": "Deny",
    "msg_started": "SIGMAI bridge started on {host}:{port}.",
    "msg_stopped": "SIGMAI bridge stopped.",
    "msg_start_failed": "Could not start the SIGMAI bridge",
    # idioma e aparência
    "language_label": "Interface language",
    "theme_label": "Appearance",
    "theme_auto": "Automatic (follows the QGIS theme)",
    "theme_light": "Light",
    "theme_dark": "Dark",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Allowed",
    "event_denied_read_only": "Blocked (read only)",
    "event_denied_by_user": "Denied by you",
    "event_denied_remembered": "Denied (category refused earlier)",
    "event_denied_limit": "Blocked (session limit)",
    "event_denied_output_root": "Blocked (folder not allowed)",
    "event_denied_never_auto": "Blocked (needs your action in the panel)",
    "event_denied_no_prompt": "Blocked (panel unavailable)",
    "event_prompt_failed": "Confirmation failed",
    "event_mode_changed": "Access mode changed",
    "event_limit_changed": "Limit changed",
    "event_output_roots_changed": "Allowed folders changed",
    "event_session_reset": "Session reset",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Cartography",
    "category_simbologia": "Symbology",
    "category_camadas": "Layers",
    "category_raster": "Raster",
    "category_vetor": "Vector",
    "category_selecao": "Selection",
    "category_processing": "Processing",
    "category_fluxos": "Workflows",
    "category_atlas": "Atlas and reports",
    "category_fontes": "Data sources",
    "category_bancos": "Databases",
    "category_geometria": "Geometry",
    "category_expressoes": "Expressions",
    "category_perfil": "Profile",
    "category_gps": "GPS",
    "category_projeto": "Project",
    "category_desc_cartography": "Create layouts, compose and export maps",
    "category_desc_cartographic_design": "Apply cartographic styles and palettes",
    "category_desc_symbology": "Change layer symbols, colours and labels",
    "category_desc_layers": "Load and export layers",
    "category_desc_layer_tree": "Reorder, group and remove project layers",
    "category_desc_raster": "Process rasters and write derived files",
    "category_desc_vector": "Geometric operations that create new layers",
    "category_desc_selection": "Select and extract features",
    "category_desc_processing": "Run QGIS Processing algorithms",
    "category_desc_workflows": "Run composite workflows",
    "category_desc_atlas_reports": "Generate atlases, series and reports",
    "category_desc_data_sources": "Connect to services and repair paths",
    "category_desc_databases": "Connect to databases and load tables",
    "category_desc_crs_quality": "Fix invalid geometries",
    "category_desc_expressions": "Evaluate QGIS expressions",
    "category_desc_user_profile": "Save the user's authorship profile",
    "category_desc_gps_gpx": "Load and convert GPX tracks",
    "category_desc_project": "Undo the assistant's last action in the project",
    "category_desc_default": "Action that changes the project or writes files",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Action",
    "consent_category": "Category",
    "consent_writes_to": "Writes to",
    "consent_params": "Parameters",
    # autoteste (passo 3)
    "selftest_bridge": "Local bridge",
    "selftest_auth": "Authentication",
    "selftest_project": "QGIS project",
    "selftest_session": "Session file",
    "selftest_mcp": "MCP server",
    "selftest_mode": "Access mode",
    "selftest_bridge_off": "The bridge is stopped. Start it in step 1.",
    "selftest_bridge_ok": "answers on {host}:{port} (plugin {version})",
    "selftest_bridge_fail": "no answer: {error}",
    "selftest_auth_leak": "the bridge accepted a request WITHOUT a token — this should never happen",
    "selftest_auth_ok": "a request without a token is refused, as expected",
    "selftest_auth_http": "unexpected HTTP {code} response",
    "selftest_project_ok": "{count} layer(s), CRS {crs}",
    "selftest_crs_undefined": "not set",
    "selftest_session_disabled": "turned off in Advanced; AI clients will not find the bridge on their own",
    "selftest_session_missing": "not found at {path}",
    "selftest_session_unreadable": "unreadable: {error}",
    "selftest_session_port": "points to port {file_port}, but the bridge is on {port}",
    "selftest_session_ok": "written and consistent with the bridge",
    "selftest_mcp_missing": "file missing: {path}",
    "selftest_mcp_no_python": "interpreter not found: {executable}",
    "selftest_mcp_ok": "{server} answered and reached the bridge, launched the way the AI client will: {python}",
    "selftest_mcp_failed": "the AI client will not be able to use SIGMAI with {python} (stage {stage}): {error}",
    "selftest_mode_read_only": "read only: the AI can inspect and simulate, but not produce maps. Change it in the Access tab whenever you like.",
    # clientes de IA (passo 2)
    "client_generic_label": "Other MCP client",
    "client_path_claude_code": ".mcp.json at the project root, or ~/.claude.json",
    "client_path_generic": "see the client's documentation",
    "client_note_claude_desktop": "Claude menu → Settings… → Developer tab → Edit Config. Fully quit and reopen Claude Desktop after saving.",
    "client_note_claude_code": "Or run the command below in your project directory.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, or edit the file directly.",
    "client_note_codex": "Append the block to the end of the configuration file.",
    "client_note_generic": "Any MCP client that speaks stdio works. The contract is: launch the command below as a subprocess and exchange newline-delimited JSON-RPC 2.0.",
}
