"""Textos da interface do SIGMAI — Español (es).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Interfaz Segura SIG-IA",
    "subtitle": "Interfaz Segura SIG-IA",
    "context": "Puente local entre asistentes de IA y QGIS",
    "online": "Conectado",
    "offline": "Detenido",
    # abas
    "tab_connection": "Conexión",
    "tab_access": "Acceso",
    "tab_activity": "Actividad",
    "tab_advanced": "Avanzado",
    "tab_help": "Ayuda",
    # aba Conexão
    "step1_title": "Inicie el puente con QGIS",
    "step1_hint": "El puente escucha solo en 127.0.0.1 y exige un token. Nada sale de su equipo.",
    "step1_start": "Iniciar puente",
    "step1_stop": "Detener puente",
    "step1_running": "Puente activo en {host}:{port} · QGIS {qgis}",
    "step1_stopped": "El puente está detenido. Haga clic en Iniciar puente.",
    "step2_title": "Configure su asistente de IA",
    "step2_hint": "Elija el programa que usa. SIGMAI arma la configuración con las rutas correctas.",
    "step2_client": "Programa",
    "step2_where": "Dónde pegarla",
    "step2_copy": "Copiar configuración",
    "step2_open_folder": "Abrir carpeta de configuración",
    "step2_copied": "Configuración copiada. Péguela en el archivo indicado y reinicie el programa.",
    "step3_title": "Compruebe que funciona",
    "step3_hint": "La prueba recorre el puente de punta a punta, como lo haría un asistente de IA.",
    "step3_run": "Probar conexión",
    "step3_running": "Probando…",
    "step3_never": "Aún no probado.",
    # aba Acesso
    "access_title": "Qué puede hacer la IA en este QGIS",
    "access_hint": "Los comandos de lectura y las simulaciones funcionan siempre. Esta elección rige las acciones que alteran el proyecto o escriben archivos.",
    "mode_read_only": "Solo lectura",
    "mode_read_only_hint": "La IA inspecciona y simula, pero nada se altera ni se escribe. Recomendado para empezar.",
    "mode_ask": "Preguntar siempre",
    "mode_ask_hint": "Cada acción que altera algo abre una confirmación que muestra exactamente qué se hará.",
    "mode_allow": "Permitir en esta sesión",
    "mode_allow_hint": "La IA ejecuta sin preguntar, dentro de las carpetas y límites definidos abajo.",
    "folders_title": "Carpetas donde la IA puede escribir",
    "folders_hint": "Vacío significa cualquier carpeta. Restringirlo es la protección más eficaz contra escrituras en el lugar equivocado.",
    "folders_add": "Agregar carpeta…",
    "folders_remove": "Quitar",
    "limits_title": "Límites de esta sesión",
    "limits_hint": "Un tope por sesión evita que un bucle del asistente genere cientos de archivos.",
    "limit_writes": "Cambios en el proyecto",
    "limit_exports": "Mapas y exportaciones",
    "limit_processing": "Ejecuciones de Processing",
    "limits_reset": "Reiniciar contadores y aprobaciones",
    # aba Atividade
    "activity_title": "Qué pidió la IA",
    "activity_hint": "Registro de las decisiones de acceso de esta sesión. Ningún token aparece aquí.",
    "activity_refresh": "Actualizar",
    "activity_export": "Exportar informe…",
    "activity_empty": "Todavía no hay solicitudes.",
    "col_time": "Cuándo",
    "col_event": "Decisión",
    "col_action": "Comando",
    "col_detail": "Detalle",
    # aba Avançado
    "advanced_endpoint": "Puente local",
    "advanced_host": "Host",
    "advanced_port": "Puerto",
    "advanced_token": "Token",
    "advanced_show": "Mostrar",
    "advanced_hide": "Ocultar",
    "advanced_copy_token": "Copiar",
    "advanced_regenerate": "Generar un token nuevo",
    "advanced_session_file": "Archivo de sesión",
    "advanced_open_logs": "Abrir carpeta de diagnóstico",
    "advanced_autostart": "Iniciar el puente junto con QGIS",
    "advanced_write_session": "Escribir el archivo de sesión para que los clientes de IA encuentren el puente",
    "advanced_persist_token": "Mantener el mismo token entre sesiones de QGIS",
    "advanced_persist_hint": "Sin esto, el token cambia cada vez que se abre QGIS y hay que rehacer la configuración del cliente.",
    "advanced_token_warning": "Trate el token como una contraseña. Quien lo tenga puede controlar este QGIS a través del puente local.",
    # Modo DEV
    "dev_title": "Modo Desarrollador",
    "dev_hint": "Habilita la ejecución de Python dentro de QGIS para desarrollar complementos. Desactivado por defecto.",
    "dev_warning": "Este modo puede corromper su QGIS: ejecuta código directamente en el intérprete de la aplicación.",
    "dev_off": "Desactivado",
    "dev_on": "ACTIVADO",
    "dev_enable": "Activar Modo DEV",
    "dev_disable": "Desactivar Modo DEV",
    "dev_dialog_title": "Activar el Modo DEV de SIGMAI",
    "dev_dialog_prompt": "Escriba YES para confirmar:",
    # aba Ajuda
    "help_title": "Cómo funciona SIGMAI",
    "help_what_title": "Qué es esto",
    "help_what": "SIGMAI abre una puerta entre QGIS y un asistente de IA. Usted conversa con el asistente en su idioma; él opera QGIS por usted y devuelve el mapa terminado. No necesita saber dónde están los menús de QGIS, ni qué son la escala, la proyección o la leyenda: SIGMAI se encarga de eso y le cuenta qué hizo.",
    "help_try_title": "Frases para empezar",
    "help_try": "• «¿Qué capas están abiertas en este proyecto?»\n• «Haz un mapa del sendero en A4, para imprimir.»\n• «Mapa del parque con los municipios de alrededor y un mapita de localización.»\n• «Pon los nombres de las unidades en el mapa.»\n• «Dos mapas en la misma hoja: el parque y el estado entero.»\n• «¿Este mapa sirve para publicar? ¿Qué le falta?»",
    "help_ask_title": "Dos cosas que el asistente le preguntará",
    "help_ask": "De dónde vienen los datos y quién firma el mapa. Sin esas dos informaciones el mapa no puede citarse en un trabajo, y SIGMAI se niega a darle la nota máxima. La autoría del mapa es suya (o de quien lo elaboró), no de este complemento.",
    "help_quality_title": "La nota del mapa",
    "help_quality": "Cada mapa generado recibe una nota de A a E, con la lista de lo que está mal y qué corrige cada punto. La nota no es una opinión: es un reglamento de reglas explícitas, cada una con su razón de existir. Pídale al asistente «explícame la nota de este mapa».",
    "help_refuse_title": "Cuándo SIGMAI se niega",
    "help_refuse": "Negarse es a propósito. Si el asistente pide un formato de página que no existe, un campo de etiqueta vacío o una carpeta donde va un archivo, SIGMAI se detiene y dice qué acepta, en vez de entregar en silencio un mapa distinto del pedido.",
    "help_privacy_title": "Dónde quedan sus datos",
    "help_privacy": "El puente escucha solo en 127.0.0.1, que es su propio equipo, y exige un token. Sus archivos no se envían a ningún lado: el asistente manda comandos, QGIS los ejecuta aquí y devuelve el resultado.",
    "help_docs": "Documentación y código: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "Acerca de SIGMAI",
    "about_plugin": "Autor del complemento: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · GNU GPL v3.0 o posterior · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "La autoría del complemento no es la autoría de los mapas: indique map_author y data_source en cada mapa generado.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "El asistente de IA quiere ejecutar una acción",
    "consent_allow": "Permitir una vez",
    "consent_allow_category": "Permitir toda esta categoría en esta sesión",
    "consent_deny": "Denegar",
    "msg_started": "Puente de SIGMAI iniciado en {host}:{port}.",
    "msg_stopped": "Puente de SIGMAI detenido.",
    "msg_start_failed": "No se pudo iniciar el puente de SIGMAI",
    # idioma e aparência
    "language_label": "Idioma de la interfaz",
    "theme_label": "Apariencia",
    "theme_auto": "Automática (sigue el tema de QGIS)",
    "theme_light": "Clara",
    "theme_dark": "Oscura",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Permitido",
    "event_denied_read_only": "Bloqueado (solo lectura)",
    "event_denied_by_user": "Denegado por usted",
    "event_denied_remembered": "Denegado (categoría rechazada antes)",
    "event_denied_limit": "Bloqueado (límite de la sesión)",
    "event_denied_output_root": "Bloqueado (carpeta no autorizada)",
    "event_denied_never_auto": "Bloqueado (requiere su acción en el panel)",
    "event_denied_no_prompt": "Bloqueado (panel no disponible)",
    "event_prompt_failed": "Fallo al confirmar",
    "event_mode_changed": "Modo de acceso cambiado",
    "event_limit_changed": "Límite cambiado",
    "event_output_roots_changed": "Carpetas autorizadas cambiadas",
    "event_session_reset": "Sesión reiniciada",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Cartografía",
    "category_simbologia": "Simbología",
    "category_camadas": "Capas",
    "category_raster": "Ráster",
    "category_vetor": "Vectorial",
    "category_selecao": "Selección",
    "category_processing": "Processing",
    "category_fluxos": "Flujos de trabajo",
    "category_atlas": "Atlas e informes",
    "category_fontes": "Fuentes de datos",
    "category_bancos": "Bases de datos",
    "category_geometria": "Geometría",
    "category_expressoes": "Expresiones",
    "category_perfil": "Perfil",
    "category_gps": "GPS",
    "category_desc_cartography": "Crear diseños, componer y exportar mapas",
    "category_desc_cartographic_design": "Aplicar estilos y paletas cartográficas",
    "category_desc_symbology": "Cambiar símbolos, colores y etiquetas de las capas",
    "category_desc_layers": "Cargar y exportar capas",
    "category_desc_layer_tree": "Reordenar, agrupar y quitar capas del proyecto",
    "category_desc_raster": "Procesar rásteres y escribir archivos derivados",
    "category_desc_vector": "Operaciones geométricas que crean capas nuevas",
    "category_desc_selection": "Seleccionar y extraer entidades",
    "category_desc_processing": "Ejecutar algoritmos de Processing de QGIS",
    "category_desc_workflows": "Ejecutar flujos de trabajo compuestos",
    "category_desc_atlas_reports": "Generar atlas, series e informes",
    "category_desc_data_sources": "Conectar a servicios y reparar rutas",
    "category_desc_databases": "Conectar a bases de datos y cargar tablas",
    "category_desc_crs_quality": "Corregir geometrías inválidas",
    "category_desc_expressions": "Evaluar expresiones de QGIS",
    "category_desc_user_profile": "Guardar el perfil de autoría del usuario",
    "category_desc_gps_gpx": "Cargar y convertir trazas GPX",
    "category_desc_default": "Acción que altera el proyecto o escribe archivos",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Acción",
    "consent_category": "Categoría",
    "consent_writes_to": "Escribe en",
    "consent_params": "Parámetros",
    # autoteste (passo 3)
    "selftest_bridge": "Puente local",
    "selftest_auth": "Autenticación",
    "selftest_project": "Proyecto QGIS",
    "selftest_session": "Archivo de sesión",
    "selftest_mcp": "Servidor MCP",
    "selftest_mode": "Modo de acceso",
    "selftest_bridge_off": "El puente está detenido. Inícielo en el paso 1.",
    "selftest_bridge_ok": "responde en {host}:{port} (complemento {version})",
    "selftest_bridge_fail": "sin respuesta: {error}",
    "selftest_auth_leak": "el puente aceptó una solicitud SIN token; esto no debería ocurrir",
    "selftest_auth_ok": "una solicitud sin token se rechaza, como se espera",
    "selftest_auth_http": "respuesta inesperada HTTP {code}",
    "selftest_project_ok": "{count} capa(s), SRC {crs}",
    "selftest_crs_undefined": "sin definir",
    "selftest_session_disabled": "desactivado en Avanzado; los clientes de IA no encontrarán el puente por sí solos",
    "selftest_session_missing": "no se encontró en {path}",
    "selftest_session_unreadable": "ilegible: {error}",
    "selftest_session_port": "apunta al puerto {file_port}, pero el puente está en el {port}",
    "selftest_session_ok": "escrito y coherente con el puente",
    "selftest_mcp_missing": "falta el archivo: {path}",
    "selftest_mcp_no_python": "intérprete no encontrado: {executable}",
    "selftest_mcp_ok": "{server} listo, con {python}",
    "selftest_mode_read_only": "solo lectura: la IA puede inspeccionar y simular, pero no generar mapas. Cámbielo en la pestaña Acceso cuando quiera.",
    # clientes de IA (passo 2)
    "client_generic_label": "Otro cliente MCP",
    "client_path_claude_code": ".mcp.json en la raíz del proyecto, o ~/.claude.json",
    "client_path_generic": "consulte la documentación del cliente",
    "client_note_claude_desktop": "Menú Claude → Settings… → pestaña Developer → Edit Config. Después de guardar, cierre Claude Desktop por completo y ábralo de nuevo.",
    "client_note_claude_code": "O ejecute el comando de abajo en la terminal, dentro del proyecto.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, o edite el archivo directamente.",
    "client_note_codex": "Agregue el bloque al final del archivo de configuración.",
    "client_note_generic": "Sirve cualquier cliente que hable MCP por stdio. El contrato es: lanzar el comando de abajo como subproceso e intercambiar JSON-RPC 2.0 delimitado por saltos de línea.",
}
