"""Textos da interface do SIGMAI — Français (fr).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Interface sécurisée SIG-IA",
    "subtitle": "Interface sécurisée SIG-IA",
    "context": "Pont local entre les assistants IA et QGIS",
    "online": "Connecté",
    "offline": "Arrêté",
    # abas
    "tab_connection": "Connexion",
    "tab_access": "Accès",
    "tab_activity": "Activité",
    "tab_advanced": "Avancé",
    "tab_help": "Aide",
    # aba Conexão
    "step1_title": "Démarrez le pont vers QGIS",
    "step1_hint": "Le pont n'écoute que sur 127.0.0.1 et exige un jeton. Rien ne quitte votre machine.",
    "step1_start": "Démarrer le pont",
    "step1_stop": "Arrêter le pont",
    "step1_running": "Pont actif sur {host}:{port} · QGIS {qgis}",
    "step1_stopped": "Le pont est arrêté. Cliquez sur Démarrer le pont.",
    "step2_title": "Configurez votre assistant IA",
    "step2_hint": "Choisissez le programme que vous utilisez. SIGMAI prépare la configuration avec les bons chemins.",
    "step2_client": "Programme",
    "step2_where": "Où la coller",
    "step2_copy": "Copier la configuration",
    "step2_open_folder": "Ouvrir le dossier de configuration",
    "step2_copied": "Configuration copiée. Collez-la dans le fichier indiqué et redémarrez le programme.",
    "step3_title": "Vérifiez que tout fonctionne",
    "step3_hint": "Le test parcourt le pont de bout en bout, comme le ferait un assistant IA.",
    "step3_run": "Tester la connexion",
    "step3_running": "Test en cours…",
    "step3_never": "Pas encore testé.",
    # aba Acesso
    "access_title": "Ce que l'IA peut faire dans ce QGIS",
    "access_hint": "Les commandes de lecture et les simulations fonctionnent toujours. Ce choix s'applique aux actions qui modifient le projet ou écrivent des fichiers.",
    "mode_read_only": "Lecture seule",
    "mode_read_only_hint": "L'IA inspecte et simule, mais rien n'est modifié ni écrit. Recommandé pour commencer.",
    "mode_ask": "Toujours demander",
    "mode_ask_hint": "Chaque action qui modifie quelque chose ouvre une confirmation montrant exactement ce qui sera fait.",
    "mode_allow": "Autoriser pour cette session",
    "mode_allow_hint": "L'IA agit sans demander, dans les dossiers et les limites définis ci-dessous.",
    "folders_title": "Dossiers où l'IA peut écrire",
    "folders_hint": "Vide signifie n'importe quel dossier. Restreindre est la protection la plus efficace contre une écriture au mauvais endroit.",
    "folders_add": "Ajouter un dossier…",
    "folders_remove": "Retirer",
    "limits_title": "Limites de cette session",
    "limits_hint": "Un plafond par session empêche une boucle de l'assistant de produire des centaines de fichiers.",
    "limit_writes": "Modifications du projet",
    "limit_exports": "Cartes et exports",
    "limit_processing": "Exécutions de Processing",
    "limits_reset": "Remettre à zéro les compteurs et les approbations",
    # aba Atividade
    "activity_title": "Ce que l'IA a demandé",
    "activity_hint": "Journal des décisions d'accès de cette session. Aucun jeton n'apparaît ici.",
    "activity_refresh": "Actualiser",
    "activity_export": "Exporter le rapport…",
    "activity_empty": "Aucune demande pour l'instant.",
    "col_time": "Quand",
    "col_event": "Décision",
    "col_action": "Commande",
    "col_detail": "Détail",
    # aba Avançado
    "advanced_endpoint": "Pont local",
    "advanced_host": "Hôte",
    "advanced_port": "Port",
    "advanced_token": "Jeton",
    "advanced_show": "Afficher",
    "advanced_hide": "Masquer",
    "advanced_copy_token": "Copier",
    "advanced_regenerate": "Générer un nouveau jeton",
    "advanced_session_file": "Fichier de session",
    "advanced_open_logs": "Ouvrir le dossier de diagnostic",
    "advanced_autostart": "Démarrer le pont en même temps que QGIS",
    "advanced_write_session": "Écrire le fichier de session pour que les clients IA trouvent le pont",
    "advanced_persist_token": "Conserver le même jeton d'une session QGIS à l'autre",
    "advanced_persist_hint": "Sans cela, le jeton change à chaque ouverture de QGIS et la configuration du client est à refaire.",
    "advanced_token_warning": "Traitez le jeton comme un mot de passe. Quiconque le détient peut piloter ce QGIS par le pont local.",
    # Modo DEV
    "dev_title": "Mode développeur",
    "dev_hint": "Autorise l'exécution de Python dans QGIS pour développer des extensions. Désactivé par défaut.",
    "dev_warning": "Ce mode peut corrompre votre QGIS : il exécute du code directement dans l'interpréteur de l'application.",
    "dev_off": "Désactivé",
    "dev_on": "ACTIVÉ",
    "dev_enable": "Activer le mode DEV",
    "dev_disable": "Désactiver le mode DEV",
    "dev_dialog_title": "Activer le mode DEV de SIGMAI",
    "dev_dialog_prompt": "Tapez YES pour confirmer :",
    # aba Ajuda
    "help_title": "Comment fonctionne SIGMAI",
    "help_what_title": "De quoi s'agit-il",
    "help_what": "SIGMAI ouvre une porte entre QGIS et un assistant IA. Vous discutez avec l'assistant dans votre langue ; il pilote QGIS pour vous et vous rend la carte terminée. Vous n'avez pas besoin de savoir où sont les menus de QGIS, ni ce que sont l'échelle, la projection ou la légende : SIGMAI s'en charge et vous dit ce qu'il a fait.",
    "help_try_title": "Des phrases pour commencer",
    "help_try": "• « Quelles couches sont ouvertes dans ce projet ? »\n• « Fais une carte du sentier en A4, pour l'imprimer. »\n• « Carte du parc avec les communes alentour et un petit carton de localisation. »\n• « Mets les noms des unités sur la carte. »\n• « Deux cartes sur la même feuille : le parc et l'État entier. »\n• « Cette carte est-elle publiable ? Que lui manque-t-il ? »",
    "help_ask_title": "Deux choses que l'assistant vous demandera",
    "help_ask": "D'où viennent les données et qui signe la carte. Sans ces deux informations, la carte ne peut pas être citée dans un travail, et SIGMAI refuse de lui donner la note maximale. L'auteur de la carte, c'est vous (ou la personne qui l'a réalisée), pas cette extension.",
    "help_quality_title": "La note de la carte",
    "help_quality": "Chaque carte produite reçoit une note de A à E, avec la liste de ce qui ne va pas et de ce qui corrige chaque point. La note n'est pas une opinion : c'est un règlement de règles explicites, chacune avec sa raison d'être. Demandez à l'assistant « explique-moi la note de cette carte ».",
    "help_refuse_title": "Quand SIGMAI refuse",
    "help_refuse": "Refuser est voulu. Si l'assistant demande un format de page qui n'existe pas, un champ d'étiquette vide ou un dossier à la place d'un fichier, SIGMAI s'arrête et dit ce qu'il accepte, au lieu de livrer en silence une carte différente de celle demandée.",
    "help_privacy_title": "Où restent vos données",
    "help_privacy": "Le pont n'écoute que sur 127.0.0.1, c'est-à-dire votre propre machine, et exige un jeton. Vos fichiers ne sont envoyés nulle part : l'assistant envoie des commandes, QGIS les exécute ici et renvoie le résultat.",
    "help_docs": "Documentation et code : github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "À propos de SIGMAI",
    "about_plugin": "Auteur de l'extension : MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · Licence MIT · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "L'auteur de l'extension n'est pas l'auteur des cartes : renseignez map_author et data_source pour chaque carte produite.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "L'assistant IA veut exécuter une action",
    "consent_allow": "Autoriser une fois",
    "consent_allow_category": "Autoriser toute cette catégorie pour cette session",
    "consent_deny": "Refuser",
    "msg_started": "Pont SIGMAI démarré sur {host}:{port}.",
    "msg_stopped": "Pont SIGMAI arrêté.",
    "msg_start_failed": "Impossible de démarrer le pont SIGMAI",
    # idioma e aparência
    "language_label": "Langue de l'interface",
    "theme_label": "Apparence",
    "theme_auto": "Automatique (suit le thème de QGIS)",
    "theme_light": "Claire",
    "theme_dark": "Sombre",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Autorisé",
    "event_denied_read_only": "Bloqué (lecture seule)",
    "event_denied_by_user": "Refusé par vous",
    "event_denied_remembered": "Refusé (catégorie déjà refusée)",
    "event_denied_limit": "Bloqué (limite de la session)",
    "event_denied_output_root": "Bloqué (dossier non autorisé)",
    "event_denied_never_auto": "Bloqué (nécessite votre action dans le panneau)",
    "event_denied_no_prompt": "Bloqué (panneau indisponible)",
    "event_prompt_failed": "Échec de la confirmation",
    "event_mode_changed": "Mode d'accès modifié",
    "event_limit_changed": "Limite modifiée",
    "event_output_roots_changed": "Dossiers autorisés modifiés",
    "event_session_reset": "Session réinitialisée",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Cartographie",
    "category_simbologia": "Symbologie",
    "category_camadas": "Couches",
    "category_raster": "Raster",
    "category_vetor": "Vecteur",
    "category_selecao": "Sélection",
    "category_processing": "Processing",
    "category_fluxos": "Flux de travail",
    "category_atlas": "Atlas et rapports",
    "category_fontes": "Sources de données",
    "category_bancos": "Bases de données",
    "category_geometria": "Géométrie",
    "category_expressoes": "Expressions",
    "category_perfil": "Profil",
    "category_gps": "GPS",
    "category_projeto": "Projet",
    "category_desc_cartography": "Créer des mises en page, composer et exporter des cartes",
    "category_desc_cartographic_design": "Appliquer des styles et des palettes cartographiques",
    "category_desc_symbology": "Modifier les symboles, les couleurs et les étiquettes des couches",
    "category_desc_layers": "Charger et exporter des couches",
    "category_desc_layer_tree": "Réordonner, grouper et retirer des couches du projet",
    "category_desc_raster": "Traiter des rasters et écrire des fichiers dérivés",
    "category_desc_vector": "Opérations géométriques qui créent de nouvelles couches",
    "category_desc_selection": "Sélectionner et extraire des entités",
    "category_desc_processing": "Exécuter des algorithmes de Processing QGIS",
    "category_desc_workflows": "Exécuter des flux de travail composés",
    "category_desc_atlas_reports": "Produire des atlas, des séries et des rapports",
    "category_desc_data_sources": "Se connecter à des services et réparer des chemins",
    "category_desc_databases": "Se connecter à des bases de données et charger des tables",
    "category_desc_crs_quality": "Corriger des géométries invalides",
    "category_desc_expressions": "Évaluer des expressions QGIS",
    "category_desc_user_profile": "Enregistrer le profil d'auteur de l'utilisateur",
    "category_desc_gps_gpx": "Charger et convertir des traces GPX",
    "category_desc_project": "Annuler la dernière action de l'assistant dans le projet",
    "category_desc_default": "Action qui modifie le projet ou écrit des fichiers",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Action",
    "consent_category": "Catégorie",
    "consent_writes_to": "Écrit dans",
    "consent_params": "Paramètres",
    # autoteste (passo 3)
    "selftest_bridge": "Pont local",
    "selftest_auth": "Authentification",
    "selftest_project": "Projet QGIS",
    "selftest_session": "Fichier de session",
    "selftest_mcp": "Serveur MCP",
    "selftest_mode": "Mode d'accès",
    "selftest_bridge_off": "Le pont est arrêté. Démarrez-le à l'étape 1.",
    "selftest_bridge_ok": "répond sur {host}:{port} (extension {version})",
    "selftest_bridge_fail": "pas de réponse : {error}",
    "selftest_auth_leak": "le pont a accepté une requête SANS jeton — cela ne devrait jamais arriver",
    "selftest_auth_ok": "une requête sans jeton est refusée, comme attendu",
    "selftest_auth_http": "réponse HTTP {code} inattendue",
    "selftest_project_ok": "{count} couche(s), SCR {crs}",
    "selftest_crs_undefined": "non défini",
    "selftest_session_disabled": "désactivé dans Avancé ; les clients IA ne trouveront pas le pont d'eux-mêmes",
    "selftest_session_missing": "introuvable dans {path}",
    "selftest_session_unreadable": "illisible : {error}",
    "selftest_session_port": "pointe vers le port {file_port}, mais le pont est sur le {port}",
    "selftest_session_ok": "écrit et cohérent avec le pont",
    "selftest_mcp_missing": "fichier manquant : {path}",
    "selftest_mcp_no_python": "interpréteur introuvable : {executable}",
    "selftest_mcp_ok": "{server} prêt, avec {python}",
    "selftest_mode_read_only": "lecture seule : l'IA peut inspecter et simuler, mais pas produire de cartes. Changez-le dans l'onglet Accès quand vous voulez.",
    # clientes de IA (passo 2)
    "client_generic_label": "Autre client MCP",
    "client_path_claude_code": ".mcp.json à la racine du projet, ou ~/.claude.json",
    "client_path_generic": "voir la documentation du client",
    "client_note_claude_desktop": "Menu Claude → Settings… → onglet Developer → Edit Config. Après l'enregistrement, quittez complètement Claude Desktop et rouvrez-le.",
    "client_note_claude_code": "Ou lancez la commande ci-dessous dans le terminal, dans le projet.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, ou modifiez le fichier directement.",
    "client_note_codex": "Ajoutez le bloc à la fin du fichier de configuration.",
    "client_note_generic": "Tout client qui parle MCP par stdio convient. Le contrat : lancer la commande ci-dessous en sous-processus et échanger du JSON-RPC 2.0 délimité par des sauts de ligne.",
}
