"""Textos da interface do SIGMAI — Italiano (it).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Interfaccia sicura GIS-IA",
    "subtitle": "Interfaccia sicura GIS-IA",
    "context": "Ponte locale tra assistenti IA e QGIS",
    "online": "Connesso",
    "offline": "Fermo",
    # abas
    "tab_connection": "Connessione",
    "tab_access": "Accesso",
    "tab_activity": "Attività",
    "tab_advanced": "Avanzate",
    "tab_help": "Aiuto",
    # aba Conexão
    "step1_title": "Avvia il ponte con QGIS",
    "step1_hint": "Il ponte ascolta solo su 127.0.0.1 e richiede un token. Nulla esce dal tuo computer.",
    "step1_start": "Avvia ponte",
    "step1_stop": "Ferma ponte",
    "step1_running": "Ponte attivo su {host}:{port} · QGIS {qgis}",
    "step1_stopped": "Il ponte è fermo. Fai clic su Avvia ponte.",
    "step2_title": "Configura il tuo assistente IA",
    "step2_hint": "Scegli il programma che usi. SIGMAI prepara la configurazione con i percorsi giusti.",
    "step2_client": "Programma",
    "step2_where": "Dove incollarla",
    "step2_copy": "Copia configurazione",
    "step2_open_folder": "Apri cartella di configurazione",
    "step2_copied": "Configurazione copiata. Incollala nel file indicato e riavvia il programma.",
    "step3_title": "Verifica che funzioni",
    "step3_hint": "Il test percorre il ponte da un capo all'altro, come farebbe un assistente IA.",
    "step3_run": "Prova connessione",
    "step3_running": "Prova in corso…",
    "step3_never": "Non ancora provato.",
    # aba Acesso
    "access_title": "Cosa può fare l'IA in questo QGIS",
    "access_hint": "I comandi di lettura e le simulazioni funzionano sempre. Questa scelta vale per le azioni che modificano il progetto o scrivono file.",
    "mode_read_only": "Sola lettura",
    "mode_read_only_hint": "L'IA ispeziona e simula, ma nulla viene modificato né scritto. Consigliato per iniziare.",
    "mode_ask": "Chiedi sempre",
    "mode_ask_hint": "Ogni azione che modifica qualcosa apre una conferma che mostra esattamente cosa verrà fatto.",
    "mode_allow": "Consenti in questa sessione",
    "mode_allow_hint": "L'IA agisce senza chiedere, entro le cartelle e i limiti definiti qui sotto.",
    "folders_title": "Cartelle in cui l'IA può scrivere",
    "folders_hint": "Vuoto significa qualsiasi cartella. Limitarle è la protezione più efficace contro scritture nel posto sbagliato.",
    "folders_add": "Aggiungi cartella…",
    "folders_remove": "Rimuovi",
    "limits_title": "Limiti di questa sessione",
    "limits_hint": "Un tetto per sessione evita che un ciclo dell'assistente generi centinaia di file.",
    "limit_writes": "Modifiche al progetto",
    "limit_exports": "Mappe ed esportazioni",
    "limit_processing": "Esecuzioni di Processing",
    "limits_reset": "Azzera contatori e approvazioni",
    # aba Atividade
    "activity_title": "Cosa ha chiesto l'IA",
    "activity_hint": "Registro delle decisioni di accesso di questa sessione. Nessun token compare qui.",
    "activity_refresh": "Aggiorna",
    "activity_export": "Esporta rapporto…",
    "activity_empty": "Nessuna richiesta finora.",
    "col_time": "Quando",
    "col_event": "Decisione",
    "col_action": "Comando",
    "col_detail": "Dettaglio",
    # aba Avançado
    "advanced_endpoint": "Ponte locale",
    "advanced_host": "Host",
    "advanced_port": "Porta",
    "advanced_token": "Token",
    "advanced_show": "Mostra",
    "advanced_hide": "Nascondi",
    "advanced_copy_token": "Copia",
    "advanced_regenerate": "Genera un nuovo token",
    "advanced_session_file": "File di sessione",
    "advanced_open_logs": "Apri cartella di diagnostica",
    "advanced_autostart": "Avvia il ponte insieme a QGIS",
    "advanced_write_session": "Scrivi il file di sessione perché i client IA trovino il ponte",
    "advanced_persist_token": "Mantieni lo stesso token tra le sessioni di QGIS",
    "advanced_persist_hint": "Senza questo, il token cambia a ogni apertura di QGIS e la configurazione del client va rifatta.",
    "advanced_token_warning": "Tratta il token come una password. Chi lo possiede può comandare questo QGIS attraverso il ponte locale.",
    # Modo DEV
    "dev_title": "Modalità sviluppatore",
    "dev_hint": "Abilita l'esecuzione di Python dentro QGIS per sviluppare plugin. Disattivata per impostazione predefinita.",
    "dev_warning": "Questa modalità può danneggiare il tuo QGIS: esegue codice direttamente nell'interprete dell'applicazione.",
    "dev_off": "Disattivata",
    "dev_on": "ATTIVA",
    "dev_enable": "Attiva modalità DEV",
    "dev_disable": "Disattiva modalità DEV",
    "dev_dialog_title": "Attivare la modalità DEV di SIGMAI",
    "dev_dialog_prompt": "Digita YES per confermare:",
    # aba Ajuda
    "help_title": "Come funziona SIGMAI",
    "help_what_title": "Che cos'è",
    "help_what": "SIGMAI apre una porta tra QGIS e un assistente IA. Tu parli con l'assistente nella tua lingua; lui usa QGIS al posto tuo e ti restituisce la mappa pronta. Non devi sapere dove sono i menu di QGIS, né cosa siano scala, proiezione o legenda: se ne occupa SIGMAI, e ti racconta cosa ha fatto.",
    "help_try_title": "Frasi per cominciare",
    "help_try": "• «Quali layer sono aperti in questo progetto?»\n• «Fai una mappa del sentiero in A4, da stampare.»\n• «Mappa del parco con i comuni intorno e una piccola mappa di localizzazione.»\n• «Metti i nomi delle unità sulla mappa.»\n• «Due mappe sullo stesso foglio: il parco e l'intero Stato.»\n• «Questa mappa va bene per la pubblicazione? Cosa le manca?»",
    "help_ask_title": "Due cose che l'assistente ti chiederà",
    "help_ask": "Da dove vengono i dati e chi firma la mappa. Senza queste due informazioni la mappa non può essere citata in un lavoro, e SIGMAI rifiuta di darle il voto massimo. L'autore della mappa sei tu (o chi l'ha realizzata), non questo plugin.",
    "help_quality_title": "Il voto della mappa",
    "help_quality": "Ogni mappa generata riceve un voto da A a E, con l'elenco di ciò che non va e di ciò che corregge ogni punto. Il voto non è un'opinione: è un regolamento di regole esplicite, ciascuna con la sua ragione d'essere. Chiedi all'assistente «spiegami il voto di questa mappa».",
    "help_refuse_title": "Quando SIGMAI rifiuta",
    "help_refuse": "Rifiutare è voluto. Se l'assistente chiede un formato di pagina che non esiste, un campo di etichetta vuoto o una cartella al posto di un file, SIGMAI si ferma e dice cosa accetta, invece di consegnare in silenzio una mappa diversa da quella richiesta.",
    "help_privacy_title": "Dove restano i tuoi dati",
    "help_privacy": "Il ponte ascolta solo su 127.0.0.1, cioè il tuo stesso computer, e richiede un token. I tuoi file non vengono inviati da nessuna parte: l'assistente manda comandi, QGIS li esegue qui e restituisce il risultato.",
    "help_docs": "Documentazione e codice: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "Informazioni su SIGMAI",
    "about_plugin": "Autore del plugin: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · GNU GPL v3.0 o successiva · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "L'autore del plugin non è l'autore delle mappe: indica map_author e data_source in ogni mappa generata.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "L'assistente IA vuole eseguire un'azione",
    "consent_allow": "Consenti una volta",
    "consent_allow_category": "Consenti tutta questa categoria in questa sessione",
    "consent_deny": "Nega",
    "msg_started": "Ponte SIGMAI avviato su {host}:{port}.",
    "msg_stopped": "Ponte SIGMAI fermato.",
    "msg_start_failed": "Impossibile avviare il ponte SIGMAI",
    # idioma e aparência
    "language_label": "Lingua dell'interfaccia",
    "theme_label": "Aspetto",
    "theme_auto": "Automatico (segue il tema di QGIS)",
    "theme_light": "Chiaro",
    "theme_dark": "Scuro",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Consentito",
    "event_denied_read_only": "Bloccato (sola lettura)",
    "event_denied_by_user": "Negato da te",
    "event_denied_remembered": "Negato (categoria rifiutata in precedenza)",
    "event_denied_limit": "Bloccato (limite della sessione)",
    "event_denied_output_root": "Bloccato (cartella non autorizzata)",
    "event_denied_never_auto": "Bloccato (richiede una tua azione nel pannello)",
    "event_denied_no_prompt": "Bloccato (pannello non disponibile)",
    "event_prompt_failed": "Conferma non riuscita",
    "event_mode_changed": "Modalità di accesso cambiata",
    "event_limit_changed": "Limite cambiato",
    "event_output_roots_changed": "Cartelle autorizzate cambiate",
    "event_session_reset": "Sessione azzerata",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Cartografia",
    "category_simbologia": "Simbologia",
    "category_camadas": "Layer",
    "category_raster": "Raster",
    "category_vetor": "Vettore",
    "category_selecao": "Selezione",
    "category_processing": "Processing",
    "category_fluxos": "Flussi di lavoro",
    "category_atlas": "Atlanti e rapporti",
    "category_fontes": "Sorgenti dati",
    "category_bancos": "Database",
    "category_geometria": "Geometria",
    "category_expressoes": "Espressioni",
    "category_perfil": "Profilo",
    "category_gps": "GPS",
    "category_desc_cartography": "Creare layout, comporre ed esportare mappe",
    "category_desc_cartographic_design": "Applicare stili e tavolozze cartografiche",
    "category_desc_symbology": "Cambiare simboli, colori ed etichette dei layer",
    "category_desc_layers": "Caricare ed esportare layer",
    "category_desc_layer_tree": "Riordinare, raggruppare e rimuovere layer del progetto",
    "category_desc_raster": "Elaborare raster e scrivere file derivati",
    "category_desc_vector": "Operazioni geometriche che creano nuovi layer",
    "category_desc_selection": "Selezionare ed estrarre elementi",
    "category_desc_processing": "Eseguire algoritmi di Processing di QGIS",
    "category_desc_workflows": "Eseguire flussi di lavoro composti",
    "category_desc_atlas_reports": "Generare atlanti, serie e rapporti",
    "category_desc_data_sources": "Connettersi a servizi e riparare percorsi",
    "category_desc_databases": "Connettersi a database e caricare tabelle",
    "category_desc_crs_quality": "Correggere geometrie non valide",
    "category_desc_expressions": "Valutare espressioni di QGIS",
    "category_desc_user_profile": "Salvare il profilo di autore dell'utente",
    "category_desc_gps_gpx": "Caricare e convertire tracce GPX",
    "category_desc_default": "Azione che modifica il progetto o scrive file",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Azione",
    "consent_category": "Categoria",
    "consent_writes_to": "Scrive in",
    "consent_params": "Parametri",
    # autoteste (passo 3)
    "selftest_bridge": "Ponte locale",
    "selftest_auth": "Autenticazione",
    "selftest_project": "Progetto QGIS",
    "selftest_session": "File di sessione",
    "selftest_mcp": "Server MCP",
    "selftest_mode": "Modalità di accesso",
    "selftest_bridge_off": "Il ponte è fermo. Avvialo al passo 1.",
    "selftest_bridge_ok": "risponde su {host}:{port} (plugin {version})",
    "selftest_bridge_fail": "nessuna risposta: {error}",
    "selftest_auth_leak": "il ponte ha accettato una richiesta SENZA token — non dovrebbe mai succedere",
    "selftest_auth_ok": "una richiesta senza token viene rifiutata, come previsto",
    "selftest_auth_http": "risposta HTTP {code} inattesa",
    "selftest_project_ok": "{count} layer, SR {crs}",
    "selftest_crs_undefined": "non definito",
    "selftest_session_disabled": "disattivato in Avanzate; i client IA non troveranno il ponte da soli",
    "selftest_session_missing": "non trovato in {path}",
    "selftest_session_unreadable": "illeggibile: {error}",
    "selftest_session_port": "punta alla porta {file_port}, ma il ponte è sulla {port}",
    "selftest_session_ok": "scritto e coerente con il ponte",
    "selftest_mcp_missing": "file mancante: {path}",
    "selftest_mcp_no_python": "interprete non trovato: {executable}",
    "selftest_mcp_ok": "{server} pronto, con {python}",
    "selftest_mode_read_only": "sola lettura: l'IA può ispezionare e simulare, ma non generare mappe. Cambiala nella scheda Accesso quando vuoi.",
    # clientes de IA (passo 2)
    "client_generic_label": "Altro client MCP",
    "client_path_claude_code": ".mcp.json nella radice del progetto, oppure ~/.claude.json",
    "client_path_generic": "consulta la documentazione del client",
    "client_note_claude_desktop": "Menu Claude → Settings… → scheda Developer → Edit Config. Dopo il salvataggio, chiudi completamente Claude Desktop e riaprilo.",
    "client_note_claude_code": "Oppure esegui il comando qui sotto nel terminale, dentro il progetto.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, oppure modifica il file direttamente.",
    "client_note_codex": "Aggiungi il blocco alla fine del file di configurazione.",
    "client_note_generic": "Va bene qualsiasi client che parli MCP via stdio. Il contratto: avviare il comando qui sotto come sottoprocesso e scambiare JSON-RPC 2.0 delimitato da ritorni a capo.",
}
