"""Textos da interface do SIGMAI — 日本語 (ja).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — 安全な GIS-AI インターフェース",
    "subtitle": "安全な GIS-AI インターフェース",
    "context": "AI アシスタントと QGIS をつなぐローカルブリッジ",
    "online": "接続中",
    "offline": "停止中",
    # abas
    "tab_connection": "接続",
    "tab_access": "アクセス",
    "tab_activity": "アクティビティ",
    "tab_advanced": "詳細設定",
    "tab_help": "ヘルプ",
    # aba Conexão
    "step1_title": "QGIS へのブリッジを起動する",
    "step1_hint": "ブリッジは 127.0.0.1 でのみ待ち受け、トークンを必須とします。データがこのコンピューターの外に出ることはありません。",
    "step1_start": "ブリッジを起動",
    "step1_stop": "ブリッジを停止",
    "step1_running": "ブリッジ稼働中 {host}:{port} · QGIS {qgis}",
    "step1_stopped": "ブリッジは停止しています。「ブリッジを起動」を押してください。",
    "step2_title": "AI アシスタントを設定する",
    "step2_hint": "お使いのプログラムを選んでください。SIGMAI が正しいパス入りの設定を作成します。",
    "step2_client": "プログラム",
    "step2_where": "貼り付け先",
    "step2_copy": "設定をコピー",
    "step2_open_folder": "設定フォルダーを開く",
    "step2_copied": "設定をコピーしました。指定のファイルに貼り付けて、プログラムを再起動してください。",
    "step3_title": "動作を確認する",
    "step3_hint": "AI アシスタントと同じ手順で、ブリッジを端から端まで確認します。",
    "step3_run": "接続をテスト",
    "step3_running": "テスト中…",
    "step3_never": "まだテストしていません。",
    # aba Acesso
    "access_title": "この QGIS で AI にできること",
    "access_hint": "読み取りコマンドとシミュレーションは常に使えます。この設定は、プロジェクトを変更したりファイルを書き込んだりする操作に適用されます。",
    "mode_read_only": "読み取り専用",
    "mode_read_only_hint": "AI は調べてシミュレーションするだけで、何も変更も書き込みもしません。最初はこれを推奨します。",
    "mode_ask": "毎回確認する",
    "mode_ask_hint": "何かを変更する操作のたびに、実行内容をそのまま示す確認画面が開きます。",
    "mode_allow": "このセッションで許可",
    "mode_allow_hint": "下で定めたフォルダーと上限の範囲内で、AI は確認なしに実行します。",
    "folders_title": "AI が書き込めるフォルダー",
    "folders_hint": "空欄はすべてのフォルダーを意味します。制限することが、誤った場所への書き込みを防ぐ最も確実な方法です。",
    "folders_add": "フォルダーを追加…",
    "folders_remove": "削除",
    "limits_title": "このセッションの上限",
    "limits_hint": "セッションごとの上限があれば、アシスタントの繰り返しで何百ものファイルが作られることを防げます。",
    "limit_writes": "プロジェクトの変更",
    "limit_exports": "地図と書き出し",
    "limit_processing": "Processing の実行",
    "limits_reset": "カウンターと承認をリセット",
    # aba Atividade
    "activity_title": "AI が要求したこと",
    "activity_hint": "このセッションのアクセス判断の記録です。トークンがここに表示されることはありません。",
    "activity_refresh": "更新",
    "activity_export": "レポートを書き出す…",
    "activity_empty": "まだ要求はありません。",
    "col_time": "時刻",
    "col_event": "判断",
    "col_action": "コマンド",
    "col_detail": "詳細",
    # aba Avançado
    "advanced_endpoint": "ローカルブリッジ",
    "advanced_host": "ホスト",
    "advanced_port": "ポート",
    "advanced_token": "トークン",
    "advanced_show": "表示",
    "advanced_hide": "隠す",
    "advanced_copy_token": "コピー",
    "advanced_regenerate": "新しいトークンを生成",
    "advanced_session_file": "セッションファイル",
    "advanced_open_logs": "診断フォルダーを開く",
    "advanced_autostart": "QGIS の起動時にブリッジも起動する",
    "advanced_write_session": "AI クライアントがブリッジを見つけられるようセッションファイルを書き出す",
    "advanced_persist_token": "QGIS のセッションをまたいで同じトークンを使う",
    "advanced_persist_hint": "オフ（既定）の場合、QGIS を開くたびにトークンが変わりますが、手順 2 で設定したクライアントはセッションファイルから新しいトークンを読み取るので、設定をやり直す必要はありません。トークンを手作業でどこかに貼り付けた場合のみオンにしてください。",
    "advanced_token_warning": "トークンはパスワードと同じように扱ってください。持っている人は誰でも、ローカルブリッジ経由でこの QGIS を操作できます。",
    # Modo DEV
    "dev_title": "開発者モード",
    "dev_hint": "プラグイン開発のために QGIS 内での Python 実行を許可します。既定では無効です。",
    "dev_warning": "このモードは QGIS を壊す可能性があります。アプリケーションのインタープリターで直接コードを実行します。",
    "dev_off": "無効",
    "dev_on": "有効",
    "dev_enable": "DEV モードを有効にする",
    "dev_disable": "DEV モードを無効にする",
    "dev_dialog_title": "SIGMAI の DEV モードを有効にする",
    "dev_dialog_prompt": "確認のため YES と入力してください:",
    # aba Ajuda
    "help_title": "SIGMAI のしくみ",
    "help_what_title": "これは何か",
    "help_what": "SIGMAI は QGIS と AI アシスタントの間に扉を開きます。あなたはアシスタントと自分の言葉で話し、アシスタントが代わりに QGIS を操作して、完成した地図を返します。QGIS のメニューの場所も、縮尺・投影法・凡例が何かも知らなくて構いません。SIGMAI がそれを引き受け、何をしたかを伝えます。",
    "help_try_title": "最初に使える言い方",
    "help_try": "• 「このプロジェクトで開いているレイヤは？」\n• 「登山道の地図を A4 で、印刷用に作って。」\n• 「公園の地図に周囲の市町村と小さな位置図を付けて。」\n• 「地図にユニットの名前を入れて。」\n• 「1 枚に地図を 2 つ：公園と州全体。」\n• 「この地図は公開できる出来？何が足りない？」",
    "help_ask_title": "アシスタントが尋ねる 2 つのこと",
    "help_ask": "データの出典と、地図の作成者です。この 2 つがないと地図は論文で引用できず、SIGMAI は最高評価を付けません。地図の著作者はあなた（または作成した人）であって、このプラグインではありません。",
    "help_quality_title": "地図の評価",
    "help_quality": "生成された地図はすべて A から E で評価され、問題点と各項目の直し方が一覧されます。評価は意見ではなく、明示的なルール集に基づくもので、各ルールには存在理由があります。アシスタントに「この地図の評価を説明して」と頼んでください。",
    "help_refuse_title": "SIGMAI が拒否するとき",
    "help_refuse": "拒否は意図的です。アシスタントが存在しない用紙サイズ、空のラベル項目、ファイルの代わりにフォルダーを要求すると、SIGMAI は止まって受け付けられるものを示します。頼まれたものと違う地図を黙って渡すことはしません。",
    "help_privacy_title": "データの置き場所",
    "help_privacy": "ブリッジは 127.0.0.1、つまりあなた自身のコンピューターでのみ待ち受け、トークンを必須とします。ファイルはどこにも送信されません。アシスタントがコマンドを送り、QGIS がここで実行して結果を返します。",
    "help_docs": "ドキュメントとコード: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "SIGMAI について",
    "about_plugin": "プラグイン作者: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · MIT ライセンス · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "プラグインの著作者は地図の著作者ではありません。生成する地図ごとに map_author と data_source を指定してください。",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "AI アシスタントが操作の実行を求めています",
    "consent_allow": "今回だけ許可",
    "consent_allow_category": "このカテゴリ全体をこのセッションで許可",
    "consent_deny": "拒否",
    "msg_started": "SIGMAI ブリッジを {host}:{port} で起動しました。",
    "msg_stopped": "SIGMAI ブリッジを停止しました。",
    "msg_start_failed": "SIGMAI ブリッジを起動できませんでした",
    # idioma e aparência
    "language_label": "インターフェースの言語",
    "theme_label": "外観",
    "theme_auto": "自動（QGIS のテーマに従う）",
    "theme_light": "ライト",
    "theme_dark": "ダーク",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "許可",
    "event_denied_read_only": "ブロック（読み取り専用）",
    "event_denied_by_user": "あなたが拒否",
    "event_denied_remembered": "拒否（以前に拒否したカテゴリ）",
    "event_denied_limit": "ブロック（セッションの上限）",
    "event_denied_output_root": "ブロック（許可されていないフォルダー）",
    "event_denied_never_auto": "ブロック（パネルでの操作が必要）",
    "event_denied_no_prompt": "ブロック（パネルが利用不可）",
    "event_prompt_failed": "確認に失敗",
    "event_mode_changed": "アクセスモードを変更",
    "event_limit_changed": "上限を変更",
    "event_output_roots_changed": "許可フォルダーを変更",
    "event_session_reset": "セッションをリセット",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "地図作成",
    "category_simbologia": "シンボロジ",
    "category_camadas": "レイヤ",
    "category_raster": "ラスタ",
    "category_vetor": "ベクタ",
    "category_selecao": "選択",
    "category_processing": "Processing",
    "category_fluxos": "ワークフロー",
    "category_atlas": "地図帳とレポート",
    "category_fontes": "データソース",
    "category_bancos": "データベース",
    "category_geometria": "ジオメトリ",
    "category_expressoes": "式",
    "category_perfil": "プロファイル",
    "category_gps": "GPS",
    "category_projeto": "プロジェクト",
    "category_desc_cartography": "レイアウトの作成、地図の構成と書き出し",
    "category_desc_cartographic_design": "地図表現のスタイルとパレットの適用",
    "category_desc_symbology": "レイヤのシンボル、色、ラベルの変更",
    "category_desc_layers": "レイヤの読み込みと書き出し",
    "category_desc_layer_tree": "プロジェクトのレイヤの並べ替え、グループ化、削除",
    "category_desc_raster": "ラスタの処理と派生ファイルの書き込み",
    "category_desc_vector": "新しいレイヤを作るジオメトリ演算",
    "category_desc_selection": "地物の選択と抽出",
    "category_desc_processing": "QGIS Processing アルゴリズムの実行",
    "category_desc_workflows": "複合ワークフローの実行",
    "category_desc_atlas_reports": "地図帳、図郭シリーズ、レポートの生成",
    "category_desc_data_sources": "サービスへの接続とパスの修復",
    "category_desc_databases": "データベースへの接続とテーブルの読み込み",
    "category_desc_crs_quality": "不正なジオメトリの修正",
    "category_desc_expressions": "QGIS 式の評価",
    "category_desc_user_profile": "利用者の著作者プロファイルの保存",
    "category_desc_gps_gpx": "GPX トラックの読み込みと変換",
    "category_desc_project": "アシスタントがプロジェクトで行った直前の操作を元に戻す",
    "category_desc_default": "プロジェクトを変更するかファイルを書き込む操作",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "操作",
    "consent_category": "カテゴリ",
    "consent_writes_to": "書き込み先",
    "consent_params": "パラメーター",
    # autoteste (passo 3)
    "selftest_bridge": "ローカルブリッジ",
    "selftest_auth": "認証",
    "selftest_project": "QGIS プロジェクト",
    "selftest_session": "セッションファイル",
    "selftest_mcp": "MCP サーバー",
    "selftest_mode": "アクセスモード",
    "selftest_bridge_off": "ブリッジは停止しています。手順 1 で起動してください。",
    "selftest_bridge_ok": "{host}:{port} で応答（プラグイン {version}）",
    "selftest_bridge_fail": "応答なし: {error}",
    "selftest_auth_leak": "ブリッジがトークンなしの要求を受け付けました — これは起きてはならないことです",
    "selftest_auth_ok": "トークンなしの要求は想定どおり拒否されます",
    "selftest_auth_http": "想定外の HTTP {code} 応答",
    "selftest_project_ok": "レイヤ {count} 件、CRS {crs}",
    "selftest_crs_undefined": "未設定",
    "selftest_session_disabled": "「詳細設定」で無効になっています。AI クライアントは自力でブリッジを見つけられません",
    "selftest_session_missing": "{path} に見つかりません",
    "selftest_session_unreadable": "読み取れません: {error}",
    "selftest_session_port": "ポート {file_port} を指していますが、ブリッジは {port} で稼働しています",
    "selftest_session_ok": "書き出し済みで、ブリッジと一致しています",
    "selftest_mcp_missing": "ファイルがありません: {path}",
    "selftest_mcp_no_python": "インタープリターが見つかりません: {executable}",
    "selftest_mcp_ok": "{server} が応答し、ブリッジに到達しました（AI クライアントと同じ方法で起動: {python}）",
    "selftest_mcp_failed": "AI クライアントは {python} で SIGMAI を使用できません（段階 {stage}）: {error}",
    "selftest_mode_read_only": "読み取り専用: AI は調査とシミュレーションはできますが、地図は生成できません。必要なときに「アクセス」タブで変更してください。",
    # clientes de IA (passo 2)
    "client_generic_label": "その他の MCP クライアント",
    "client_path_claude_code": "プロジェクトのルートの .mcp.json、または ~/.claude.json",
    "client_path_generic": "クライアントのドキュメントを参照してください",
    "client_note_claude_desktop": "Claude メニュー → Settings… → Developer タブ → Edit Config。保存後、Claude Desktop を完全に終了してから開き直してください。",
    "client_note_claude_code": "または、プロジェクト内のターミナルで下のコマンドを実行してください。",
    "client_note_cursor": "Settings → MCP → Add new MCP server、またはファイルを直接編集してください。",
    "client_note_codex": "設定ファイルの末尾にこのブロックを追加してください。",
    "client_note_generic": "stdio で MCP を話せるクライアントなら何でも使えます。取り決めは、下のコマンドをサブプロセスとして起動し、改行区切りの JSON-RPC 2.0 をやり取りすることです。",
}
