"""Textos da interface do SIGMAI — Português (Brasil) (pt-BR).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — Interface Segura GIS-IA",
    "subtitle": "Interface Segura GIS-IA",
    "context": "Ponte local entre assistentes de IA e o QGIS",
    "online": "Conectado",
    "offline": "Desligado",
    # abas
    "tab_connection": "Conexão",
    "tab_access": "Acesso",
    "tab_activity": "Atividade",
    "tab_advanced": "Avançado",
    "tab_help": "Ajuda",
    # aba Conexão
    "step1_title": "Ligue a ponte com o QGIS",
    "step1_hint": "A ponte escuta apenas em 127.0.0.1 e exige um token. Nada sai da sua máquina.",
    "step1_start": "Iniciar ponte",
    "step1_stop": "Parar ponte",
    "step1_running": "Ponte ativa em {host}:{port} · QGIS {qgis}",
    "step1_stopped": "A ponte está desligada. Clique em Iniciar ponte.",
    "step2_title": "Configure seu assistente de IA",
    "step2_hint": "Escolha o programa que você usa. O SIGMAI monta a configuração com os caminhos certos.",
    "step2_client": "Programa",
    "step2_where": "Onde colar",
    "step2_copy": "Copiar configuração",
    "step2_open_folder": "Abrir pasta de configuração",
    "step2_copied": "Configuração copiada. Cole no arquivo indicado e reinicie o programa.",
    "step3_title": "Confira se está funcionando",
    "step3_hint": "O teste percorre a ponte de ponta a ponta, como um assistente de IA faria.",
    "step3_run": "Testar conexão",
    "step3_running": "Testando…",
    "step3_never": "Ainda não testado.",
    # aba Acesso
    "access_title": "O que a IA pode fazer neste QGIS",
    "access_hint": "Comandos de leitura e simulações funcionam sempre. Esta escolha vale para ações que alteram o projeto ou gravam arquivos.",
    "mode_read_only": "Somente leitura",
    "mode_read_only_hint": "A IA inspeciona e simula, mas nada é alterado nem gravado. Recomendado para começar.",
    "mode_ask": "Perguntar sempre",
    "mode_ask_hint": "Cada ação que altera algo abre uma confirmação mostrando exatamente o que será feito.",
    "mode_allow": "Liberar nesta sessão",
    "mode_allow_hint": "A IA executa sem perguntar, dentro das pastas e limites definidos abaixo.",
    "folders_title": "Pastas onde a IA pode gravar",
    "folders_hint": "Vazio significa qualquer pasta. Restringir é a proteção mais eficaz contra gravação em lugar errado.",
    "folders_add": "Adicionar pasta…",
    "folders_remove": "Remover",
    "limits_title": "Limites desta sessão",
    "limits_hint": "Um teto por sessão evita que um laço de repetição do assistente gere centenas de arquivos.",
    "limit_writes": "Alterações no projeto",
    "limit_exports": "Mapas e exportações",
    "limit_processing": "Execuções de Processing",
    "limits_reset": "Zerar contadores e aprovações",
    # aba Atividade
    "activity_title": "O que a IA pediu",
    "activity_hint": "Registro das decisões de acesso desta sessão. Nenhum token aparece aqui.",
    "activity_refresh": "Atualizar",
    "activity_export": "Exportar relatório…",
    "activity_empty": "Nenhuma solicitação ainda.",
    "col_time": "Quando",
    "col_event": "Decisão",
    "col_action": "Comando",
    "col_detail": "Detalhe",
    # aba Avançado
    "advanced_endpoint": "Ponte local",
    "advanced_host": "Host",
    "advanced_port": "Porta",
    "advanced_token": "Token",
    "advanced_show": "Mostrar",
    "advanced_hide": "Ocultar",
    "advanced_copy_token": "Copiar",
    "advanced_regenerate": "Gerar novo token",
    "advanced_session_file": "Arquivo de sessão",
    "advanced_open_logs": "Abrir pasta de diagnóstico",
    "advanced_autostart": "Iniciar a ponte junto com o QGIS",
    "advanced_write_session": "Gravar o arquivo de sessão para os clientes de IA encontrarem a ponte",
    "advanced_persist_token": "Manter o mesmo token entre sessões do QGIS",
    "advanced_persist_hint": "Desligado (o padrão), o token muda a cada abertura do QGIS e os clientes configurados no passo 2 leem o novo token do arquivo de sessão, sem refazer nada. Ligue só se você colou o token à mão em algum lugar.",
    "advanced_token_warning": "Trate o token como senha. Quem o tiver pode comandar este QGIS pela ponte local.",
    # Modo DEV
    "dev_title": "Modo Desenvolvedor",
    "dev_hint": "Libera execução de Python dentro do QGIS para desenvolver plugins. Desligado por padrão.",
    "dev_warning": "Este modo pode corromper o seu QGIS: ele executa código diretamente no interpretador da ferramenta.",
    "dev_off": "Desligado",
    "dev_on": "LIGADO",
    "dev_enable": "Ativar Modo DEV",
    "dev_disable": "Desativar Modo DEV",
    "dev_dialog_title": "Ativar o Modo DEV do SIGMAI",
    "dev_dialog_prompt": "Digite SIM para confirmar:",
    # aba Ajuda
    "help_title": "Como o SIGMAI funciona",
    "help_what_title": "O que é isto",
    "help_what": "O SIGMAI abre uma porta entre o QGIS e um assistente de IA. Você conversa com o assistente em português; ele opera o QGIS por você e devolve o mapa pronto. Você não precisa saber onde ficam os menus do QGIS, nem o que é escala, projeção ou legenda — o SIGMAI cuida disso e conta o que fez.",
    "help_try_title": "Frases para começar",
    "help_try": "• “Quais camadas estão abertas neste projeto?”\n• “Faça um mapa da trilha em A4, para eu imprimir.”\n• “Mapa do parque mostrando os municípios em volta, com um mapinha de localização.”\n• “Coloque os nomes das unidades no mapa.”\n• “Dois mapas na mesma folha: o parque e o estado inteiro.”\n• “Esse mapa está bom para publicar? O que falta nele?”",
    "help_ask_title": "Duas coisas que o assistente vai perguntar",
    "help_ask": "De onde vieram os dados e quem assina o mapa. Sem essas duas informações o mapa não pode ser citado num trabalho, e o SIGMAI recusa dar nota máxima. A autoria do mapa é sua (ou de quem o elaborou) — não é a autoria deste plugin.",
    "help_quality_title": "A nota do mapa",
    "help_quality": "Todo mapa gerado recebe uma nota de A a E, com a lista do que está errado e o que corrige cada item. A nota não é opinião: é um regulamento de regras explícitas, cada uma com o motivo de existir. Peça ao assistente “me explique a nota deste mapa”.",
    "help_refuse_title": "Quando o SIGMAI recusa",
    "help_refuse": "Recusar é proposital. Se o assistente pedir um formato de página que não existe, um campo de rótulo vazio ou uma pasta no lugar do arquivo, o SIGMAI para e diz o que aceita — em vez de entregar, calado, um mapa diferente do que foi pedido.",
    "help_privacy_title": "Onde os seus dados ficam",
    "help_privacy": "A ponte escuta apenas em 127.0.0.1, que é a sua própria máquina, e exige um token. Os seus arquivos não são enviados para lugar nenhum: o assistente manda comandos, o QGIS executa aqui e devolve o resultado.",
    "help_docs": "Documentação e código: github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "Sobre o SIGMAI",
    "about_plugin": "Plugin author: MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · Licença MIT · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "A autoria do plugin não é a autoria dos mapas: informe map_author e data_source em cada mapa gerado.",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "O assistente de IA quer executar uma ação",
    "consent_allow": "Permitir uma vez",
    "consent_allow_category": "Permitir tudo desta categoria nesta sessão",
    "consent_deny": "Negar",
    "msg_started": "Ponte do SIGMAI iniciada em {host}:{port}.",
    "msg_stopped": "Ponte do SIGMAI parada.",
    "msg_start_failed": "Não foi possível iniciar a ponte do SIGMAI",
    # idioma e aparência
    "language_label": "Idioma da interface",
    "theme_label": "Aparência",
    "theme_auto": "Automática (segue o tema do QGIS)",
    "theme_light": "Clara",
    "theme_dark": "Escura",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "Permitido",
    "event_denied_read_only": "Bloqueado (somente leitura)",
    "event_denied_by_user": "Negado por você",
    "event_denied_remembered": "Negado (categoria recusada antes)",
    "event_denied_limit": "Bloqueado (limite da sessão)",
    "event_denied_output_root": "Bloqueado (pasta não autorizada)",
    "event_denied_never_auto": "Bloqueado (exige ação sua no painel)",
    "event_denied_no_prompt": "Bloqueado (painel indisponível)",
    "event_prompt_failed": "Falha ao confirmar",
    "event_mode_changed": "Modo de acesso alterado",
    "event_limit_changed": "Limite alterado",
    "event_output_roots_changed": "Pastas autorizadas alteradas",
    "event_session_reset": "Sessão reiniciada",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "Cartografia",
    "category_simbologia": "Simbologia",
    "category_camadas": "Camadas",
    "category_raster": "Raster",
    "category_vetor": "Vetor",
    "category_selecao": "Seleção",
    "category_processing": "Processing",
    "category_fluxos": "Fluxos",
    "category_atlas": "Atlas e relatórios",
    "category_fontes": "Fontes de dados",
    "category_bancos": "Bancos de dados",
    "category_geometria": "Geometria",
    "category_expressoes": "Expressões",
    "category_perfil": "Perfil",
    "category_gps": "GPS",
    "category_projeto": "Projeto",
    "category_desc_cartography": "Criar layouts, compor e exportar mapas",
    "category_desc_cartographic_design": "Aplicar estilos e paletas cartográficas",
    "category_desc_symbology": "Alterar símbolos, cores e rótulos das camadas",
    "category_desc_layers": "Carregar e exportar camadas",
    "category_desc_layer_tree": "Reorganizar, agrupar e remover camadas do projeto",
    "category_desc_raster": "Processar rasters e gravar arquivos derivados",
    "category_desc_vector": "Operações geométricas que criam novas camadas",
    "category_desc_selection": "Selecionar e extrair feições",
    "category_desc_processing": "Executar algoritmos do Processing do QGIS",
    "category_desc_workflows": "Executar fluxos de trabalho compostos",
    "category_desc_atlas_reports": "Gerar atlas, séries e relatórios",
    "category_desc_data_sources": "Conectar a serviços e reparar caminhos",
    "category_desc_databases": "Conectar a bancos e carregar tabelas",
    "category_desc_crs_quality": "Corrigir geometrias inválidas",
    "category_desc_expressions": "Avaliar expressões do QGIS",
    "category_desc_user_profile": "Gravar o perfil de autoria do usuário",
    "category_desc_gps_gpx": "Carregar e converter trilhas GPX",
    "category_desc_project": "Desfazer a última ação do assistente no projeto",
    "category_desc_default": "Ação que altera o projeto ou grava arquivos",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "Ação",
    "consent_category": "Categoria",
    "consent_writes_to": "Grava em",
    "consent_params": "Parâmetros",
    # autoteste (passo 3)
    "selftest_bridge": "Ponte local",
    "selftest_auth": "Autenticação",
    "selftest_project": "Projeto QGIS",
    "selftest_session": "Arquivo de sessão",
    "selftest_mcp": "Servidor MCP",
    "selftest_mode": "Modo de acesso",
    "selftest_bridge_off": "A ponte está desligada. Inicie no passo 1.",
    "selftest_bridge_ok": "responde em {host}:{port} (plugin {version})",
    "selftest_bridge_fail": "sem resposta: {error}",
    "selftest_auth_leak": "a ponte aceitou uma requisição SEM token — isto não deveria acontecer",
    "selftest_auth_ok": "requisição sem token é recusada, como esperado",
    "selftest_auth_http": "resposta inesperada HTTP {code}",
    "selftest_project_ok": "{count} camada(s), CRS {crs}",
    "selftest_crs_undefined": "não definido",
    "selftest_session_disabled": "desligado em Avançado; os clientes de IA não vão encontrar a ponte sozinhos",
    "selftest_session_missing": "não encontrado em {path}",
    "selftest_session_unreadable": "ilegível: {error}",
    "selftest_session_port": "aponta para a porta {file_port}, mas a ponte está na {port}",
    "selftest_session_ok": "gravado e coerente com a ponte",
    "selftest_mcp_missing": "arquivo ausente: {path}",
    "selftest_mcp_no_python": "interpretador não encontrado: {executable}",
    "selftest_mcp_ok": "{server} respondeu e alcançou a ponte, lançado como o cliente de IA lançará: {python}",
    "selftest_mcp_failed": "o cliente de IA não conseguirá usar o SIGMAI com {python} (etapa {stage}): {error}",
    "selftest_mode_read_only": "somente leitura: a IA pode inspecionar e simular, mas não gerar mapas. Mude na aba Acesso quando quiser.",
    # clientes de IA (passo 2)
    "client_generic_label": "Outro cliente MCP",
    "client_path_claude_code": ".mcp.json na raiz do projeto, ou ~/.claude.json",
    "client_path_generic": "consulte a documentação do cliente",
    "client_note_claude_desktop": "Menu Claude → Settings… → aba Developer → Edit Config. Depois de salvar, feche o Claude Desktop por completo e abra de novo.",
    "client_note_claude_code": "Ou rode o comando abaixo no terminal, dentro do projeto.",
    "client_note_cursor": "Settings → MCP → Add new MCP server, ou edite o arquivo diretamente.",
    "client_note_codex": "Acrescente o bloco ao final do arquivo de configuração.",
    "client_note_generic": "Qualquer cliente que fale MCP por stdio serve. O contrato é: lançar o comando abaixo como subprocesso e trocar JSON-RPC 2.0 delimitado por quebras de linha.",
}
