"""Textos da interface do SIGMAI — 繁體中文 (zh-Hant).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — 安全的 GIS-AI 介面",
    "subtitle": "安全的 GIS-AI 介面",
    "context": "連接 AI 助理與 QGIS 的本機橋接",
    "online": "已連線",
    "offline": "已停止",
    # abas
    "tab_connection": "連線",
    "tab_access": "存取",
    "tab_activity": "活動",
    "tab_advanced": "進階",
    "tab_help": "說明",
    # aba Conexão
    "step1_title": "啟動通往 QGIS 的橋接",
    "step1_hint": "橋接只在 127.0.0.1 上監聽，且必須使用權杖。任何資料都不會離開您的電腦。",
    "step1_start": "啟動橋接",
    "step1_stop": "停止橋接",
    "step1_running": "橋接執行於 {host}:{port} · QGIS {qgis}",
    "step1_stopped": "橋接已停止。請點選「啟動橋接」。",
    "step2_title": "設定您的 AI 助理",
    "step2_hint": "選擇您使用的程式。SIGMAI 會產生含正確路徑的設定。",
    "step2_client": "程式",
    "step2_where": "貼上位置",
    "step2_copy": "複製設定",
    "step2_open_folder": "開啟設定資料夾",
    "step2_copied": "設定已複製。請貼到指定檔案中，然後重新啟動該程式。",
    "step3_title": "檢查是否正常運作",
    "step3_hint": "測試會像 AI 助理一樣，把橋接從頭到尾走一遍。",
    "step3_run": "測試連線",
    "step3_running": "測試中…",
    "step3_never": "尚未測試。",
    # aba Acesso
    "access_title": "AI 在此 QGIS 中可以做什麼",
    "access_hint": "讀取命令與模擬執行永遠可用。此選項針對的是修改專案或寫入檔案的操作。",
    "mode_read_only": "唯讀",
    "mode_read_only_hint": "AI 只檢查與模擬，不修改也不寫入任何內容。建議初次使用時選擇。",
    "mode_ask": "每次詢問",
    "mode_ask_hint": "每個修改操作都會開啟確認視窗，準確顯示將要執行的內容。",
    "mode_allow": "本次工作階段允許",
    "mode_allow_hint": "AI 在下方設定的資料夾與上限範圍內直接執行，不再詢問。",
    "folders_title": "AI 可寫入的資料夾",
    "folders_hint": "留空表示任何資料夾。加以限制是防止寫錯位置最有效的保護。",
    "folders_add": "新增資料夾…",
    "folders_remove": "移除",
    "limits_title": "本次工作階段的上限",
    "limits_hint": "每個工作階段設定上限，可避免助理陷入迴圈而產生成百上千個檔案。",
    "limit_writes": "專案修改",
    "limit_exports": "地圖與匯出",
    "limit_processing": "Processing 執行次數",
    "limits_reset": "重設計數器與授權",
    # aba Atividade
    "activity_title": "AI 要求了什麼",
    "activity_hint": "本次工作階段存取決定的記錄。權杖絕不會出現在這裡。",
    "activity_refresh": "重新整理",
    "activity_export": "匯出報告…",
    "activity_empty": "尚無要求。",
    "col_time": "時間",
    "col_event": "決定",
    "col_action": "命令",
    "col_detail": "詳細資訊",
    # aba Avançado
    "advanced_endpoint": "本機橋接",
    "advanced_host": "主機",
    "advanced_port": "連接埠",
    "advanced_token": "權杖",
    "advanced_show": "顯示",
    "advanced_hide": "隱藏",
    "advanced_copy_token": "複製",
    "advanced_regenerate": "產生新權杖",
    "advanced_session_file": "工作階段檔案",
    "advanced_open_logs": "開啟診斷資料夾",
    "advanced_autostart": "隨 QGIS 一起啟動橋接",
    "advanced_write_session": "寫入工作階段檔案，讓 AI 用戶端能找到橋接",
    "advanced_persist_token": "在多次 QGIS 工作階段之間保持同一權杖",
    "advanced_persist_hint": "若不啟用，每次開啟 QGIS 權杖都會改變，用戶端設定必須重做。",
    "advanced_token_warning": "請像對待密碼一樣對待權杖。持有它的人都能透過本機橋接操控此 QGIS。",
    # Modo DEV
    "dev_title": "開發者模式",
    "dev_hint": "允許在 QGIS 內執行 Python，用於開發外掛。預設關閉。",
    "dev_warning": "此模式可能損壞您的 QGIS：它直接在應用程式的直譯器中執行程式碼。",
    "dev_off": "已關閉",
    "dev_on": "已開啟",
    "dev_enable": "開啟 DEV 模式",
    "dev_disable": "關閉 DEV 模式",
    "dev_dialog_title": "開啟 SIGMAI 的 DEV 模式",
    "dev_dialog_prompt": "請輸入 YES 以確認：",
    # aba Ajuda
    "help_title": "SIGMAI 的運作方式",
    "help_what_title": "這是什麼",
    "help_what": "SIGMAI 在 QGIS 與 AI 助理之間打開一扇門。您用自己的語言與助理交談，它替您操作 QGIS，並交回做好的地圖。您不需要知道 QGIS 的選單在哪裡，也不需要懂比例尺、投影或圖例——SIGMAI 會處理這些，並告訴您它做了什麼。",
    "help_try_title": "可以從這些話開始",
    "help_try": "• 「這個專案裡開啟了哪些圖層？」\n• 「把步道做成一張 A4 地圖，我要列印。」\n• 「公園地圖，顯示周邊的市鎮，再加一張小的位置圖。」\n• 「把各單元的名稱標到地圖上。」\n• 「同一頁放兩張地圖：公園和整個州。」\n• 「這張地圖能發表嗎？還缺什麼？」",
    "help_ask_title": "助理會問您的兩件事",
    "help_ask": "資料來自哪裡，以及誰署名這張地圖。沒有這兩項資訊，地圖就不能在論文中引用，SIGMAI 也不會給出最高評等。地圖的作者是您（或製作它的人），而不是這個外掛。",
    "help_quality_title": "地圖評等",
    "help_quality": "每張產生的地圖都會得到 A 到 E 的評等，並列出問題所在以及每一項的修正方法。評等不是主觀意見，而是一套明確的規則，每條規則都有其存在的理由。您可以請助理「解釋一下這張地圖的評等」。",
    "help_refuse_title": "SIGMAI 何時會拒絕",
    "help_refuse": "拒絕是有意為之。如果助理要求一種不存在的頁面尺寸、一個空的標籤欄位，或者把資料夾當作檔案，SIGMAI 會停下並說明它接受什麼——而不是默默交出一張與要求不符的地圖。",
    "help_privacy_title": "您的資料在哪裡",
    "help_privacy": "橋接只在 127.0.0.1（也就是您自己的電腦）上監聽，且必須使用權杖。您的檔案不會被傳送到任何地方：助理送出命令，QGIS 在本機執行並回傳結果。",
    "help_docs": "文件與程式碼：github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "關於 SIGMAI",
    "about_plugin": "外掛作者：MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · GNU GPL v3.0 或更新版本 · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "外掛作者不是地圖作者：請為每張產生的地圖填寫 map_author 與 data_source。",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "AI 助理要求執行一項操作",
    "consent_allow": "允許一次",
    "consent_allow_category": "本次工作階段允許此類別的全部操作",
    "consent_deny": "拒絕",
    "msg_started": "SIGMAI 橋接已在 {host}:{port} 啟動。",
    "msg_stopped": "SIGMAI 橋接已停止。",
    "msg_start_failed": "無法啟動 SIGMAI 橋接",
    # idioma e aparência
    "language_label": "介面語言",
    "theme_label": "外觀",
    "theme_auto": "自動（跟隨 QGIS 主題）",
    "theme_light": "淺色",
    "theme_dark": "深色",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "已允許",
    "event_denied_read_only": "已封鎖（唯讀）",
    "event_denied_by_user": "被您拒絕",
    "event_denied_remembered": "已拒絕（此類別先前已被拒絕）",
    "event_denied_limit": "已封鎖（工作階段上限）",
    "event_denied_output_root": "已封鎖（資料夾未授權）",
    "event_denied_never_auto": "已封鎖（需要您在面板中操作）",
    "event_denied_no_prompt": "已封鎖（面板無法使用）",
    "event_prompt_failed": "確認失敗",
    "event_mode_changed": "存取模式已變更",
    "event_limit_changed": "上限已變更",
    "event_output_roots_changed": "授權資料夾已變更",
    "event_session_reset": "工作階段已重設",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "製圖",
    "category_simbologia": "符號化",
    "category_camadas": "圖層",
    "category_raster": "網格",
    "category_vetor": "向量",
    "category_selecao": "選取",
    "category_processing": "Processing",
    "category_fluxos": "工作流程",
    "category_atlas": "圖集與報告",
    "category_fontes": "資料來源",
    "category_bancos": "資料庫",
    "category_geometria": "幾何",
    "category_expressoes": "運算式",
    "category_perfil": "作者檔案",
    "category_gps": "GPS",
    "category_desc_cartography": "建立版面配置、編排並匯出地圖",
    "category_desc_cartographic_design": "套用製圖樣式與配色",
    "category_desc_symbology": "變更圖層的符號、顏色與標籤",
    "category_desc_layers": "載入與匯出圖層",
    "category_desc_layer_tree": "重新排列、分組與移除專案中的圖層",
    "category_desc_raster": "處理網格並寫入衍生檔案",
    "category_desc_vector": "產生新圖層的幾何運算",
    "category_desc_selection": "選取並擷取圖徵",
    "category_desc_processing": "執行 QGIS Processing 演算法",
    "category_desc_workflows": "執行組合工作流程",
    "category_desc_atlas_reports": "產生圖集、圖幅系列與報告",
    "category_desc_data_sources": "連線至服務並修復路徑",
    "category_desc_databases": "連線至資料庫並載入資料表",
    "category_desc_crs_quality": "修正無效幾何",
    "category_desc_expressions": "評估 QGIS 運算式",
    "category_desc_user_profile": "儲存使用者的作者檔案",
    "category_desc_gps_gpx": "載入並轉換 GPX 軌跡",
    "category_desc_default": "修改專案或寫入檔案的操作",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "操作",
    "consent_category": "類別",
    "consent_writes_to": "寫入位置",
    "consent_params": "參數",
    # autoteste (passo 3)
    "selftest_bridge": "本機橋接",
    "selftest_auth": "身分驗證",
    "selftest_project": "QGIS 專案",
    "selftest_session": "工作階段檔案",
    "selftest_mcp": "MCP 伺服器",
    "selftest_mode": "存取模式",
    "selftest_bridge_off": "橋接已停止。請在步驟 1 中啟動。",
    "selftest_bridge_ok": "在 {host}:{port} 回應（外掛 {version}）",
    "selftest_bridge_fail": "無回應：{error}",
    "selftest_auth_leak": "橋接接受了一個沒有權杖的要求——這絕不應該發生",
    "selftest_auth_ok": "沒有權杖的要求已如預期被拒絕",
    "selftest_auth_http": "非預期的 HTTP {code} 回應",
    "selftest_project_ok": "{count} 個圖層，CRS {crs}",
    "selftest_crs_undefined": "未設定",
    "selftest_session_disabled": "已在「進階」中關閉；AI 用戶端將無法自行找到橋接",
    "selftest_session_missing": "在 {path} 找不到",
    "selftest_session_unreadable": "無法讀取：{error}",
    "selftest_session_port": "指向連接埠 {file_port}，但橋接執行於 {port}",
    "selftest_session_ok": "已寫入，且與橋接一致",
    "selftest_mcp_missing": "檔案遺失：{path}",
    "selftest_mcp_no_python": "找不到直譯器：{executable}",
    "selftest_mcp_ok": "{server} 已就緒，使用 {python}",
    "selftest_mode_read_only": "唯讀：AI 可以檢查與模擬，但不能產生地圖。需要時可在「存取」分頁中變更。",
    # clientes de IA (passo 2)
    "client_generic_label": "其他 MCP 用戶端",
    "client_path_claude_code": "專案根目錄下的 .mcp.json，或 ~/.claude.json",
    "client_path_generic": "請參閱該用戶端的文件",
    "client_note_claude_desktop": "Claude 選單 → Settings… → Developer 分頁 → Edit Config。儲存後，請完全結束 Claude Desktop 再重新開啟。",
    "client_note_claude_code": "或者在專案目錄內的終端機中執行下面的命令。",
    "client_note_cursor": "Settings → MCP → Add new MCP server，或直接編輯該檔案。",
    "client_note_codex": "把這段內容附加到設定檔的結尾。",
    "client_note_generic": "任何透過 stdio 使用 MCP 的用戶端都可以。約定是：以子程序方式啟動下面的命令，並交換以換行分隔的 JSON-RPC 2.0。",
}
