"""Textos da interface do SIGMAI — 简体中文 (zh-Hans).

Gerado e conferido junto das demais línguas: toda chave de pt_br.py existe
aqui, com os mesmos marcadores de formatação. Ver sigmai/ui/strings/__init__.py.
"""

from __future__ import annotations

STRINGS: dict[str, str] = {
    # cabeçalho e estado
    "window_title": "SIGMAI — 安全的 GIS-AI 接口",
    "subtitle": "安全的 GIS-AI 接口",
    "context": "连接 AI 助手与 QGIS 的本地桥接",
    "online": "已连接",
    "offline": "已停止",
    # abas
    "tab_connection": "连接",
    "tab_access": "访问",
    "tab_activity": "活动",
    "tab_advanced": "高级",
    "tab_help": "帮助",
    # aba Conexão
    "step1_title": "启动通往 QGIS 的桥接",
    "step1_hint": "桥接只在 127.0.0.1 上监听，并且必须使用令牌。任何数据都不会离开您的电脑。",
    "step1_start": "启动桥接",
    "step1_stop": "停止桥接",
    "step1_running": "桥接运行于 {host}:{port} · QGIS {qgis}",
    "step1_stopped": "桥接已停止。请点击“启动桥接”。",
    "step2_title": "配置您的 AI 助手",
    "step2_hint": "选择您使用的程序。SIGMAI 会生成带有正确路径的配置。",
    "step2_client": "程序",
    "step2_where": "粘贴位置",
    "step2_copy": "复制配置",
    "step2_open_folder": "打开配置文件夹",
    "step2_copied": "配置已复制。请粘贴到指定文件中，然后重启该程序。",
    "step3_title": "检查是否正常工作",
    "step3_hint": "测试会像 AI 助手一样，把桥接从头到尾走一遍。",
    "step3_run": "测试连接",
    "step3_running": "测试中…",
    "step3_never": "尚未测试。",
    # aba Acesso
    "access_title": "AI 在此 QGIS 中可以做什么",
    "access_hint": "读取命令和模拟运行始终可用。此选项针对的是修改工程或写入文件的操作。",
    "mode_read_only": "只读",
    "mode_read_only_hint": "AI 只检查和模拟，不修改也不写入任何内容。建议初次使用时选择。",
    "mode_ask": "每次询问",
    "mode_ask_hint": "每个修改操作都会弹出确认框，准确显示将要执行的内容。",
    "mode_allow": "本次会话允许",
    "mode_allow_hint": "AI 在下方设定的文件夹和上限范围内直接执行，不再询问。",
    "folders_title": "AI 可写入的文件夹",
    "folders_hint": "留空表示任何文件夹。加以限制是防止写错位置的最有效保护。",
    "folders_add": "添加文件夹…",
    "folders_remove": "移除",
    "limits_title": "本次会话的上限",
    "limits_hint": "每个会话设置上限，可以避免助手陷入循环而生成成百上千个文件。",
    "limit_writes": "工程修改",
    "limit_exports": "地图与导出",
    "limit_processing": "Processing 运行次数",
    "limits_reset": "重置计数器与授权",
    # aba Atividade
    "activity_title": "AI 请求了什么",
    "activity_hint": "本次会话访问决定的记录。令牌绝不会出现在这里。",
    "activity_refresh": "刷新",
    "activity_export": "导出报告…",
    "activity_empty": "尚无请求。",
    "col_time": "时间",
    "col_event": "决定",
    "col_action": "命令",
    "col_detail": "详情",
    # aba Avançado
    "advanced_endpoint": "本地桥接",
    "advanced_host": "主机",
    "advanced_port": "端口",
    "advanced_token": "令牌",
    "advanced_show": "显示",
    "advanced_hide": "隐藏",
    "advanced_copy_token": "复制",
    "advanced_regenerate": "生成新令牌",
    "advanced_session_file": "会话文件",
    "advanced_open_logs": "打开诊断文件夹",
    "advanced_autostart": "随 QGIS 一起启动桥接",
    "advanced_write_session": "写入会话文件，让 AI 客户端能找到桥接",
    "advanced_persist_token": "在多次 QGIS 会话之间保持同一令牌",
    "advanced_persist_hint": "若不启用，每次打开 QGIS 令牌都会改变，客户端配置需要重做。",
    "advanced_token_warning": "请像对待密码一样对待令牌。持有它的人都能通过本地桥接操控此 QGIS。",
    # Modo DEV
    "dev_title": "开发者模式",
    "dev_hint": "允许在 QGIS 内执行 Python，用于开发插件。默认关闭。",
    "dev_warning": "此模式可能损坏您的 QGIS：它直接在应用程序的解释器中运行代码。",
    "dev_off": "已关闭",
    "dev_on": "已开启",
    "dev_enable": "开启 DEV 模式",
    "dev_disable": "关闭 DEV 模式",
    "dev_dialog_title": "开启 SIGMAI 的 DEV 模式",
    "dev_dialog_prompt": "请输入 YES 以确认：",
    # aba Ajuda
    "help_title": "SIGMAI 的工作原理",
    "help_what_title": "这是什么",
    "help_what": "SIGMAI 在 QGIS 与 AI 助手之间打开一扇门。您用自己的语言与助手交谈，它替您操作 QGIS，并交回做好的地图。您不需要知道 QGIS 的菜单在哪里，也不需要懂比例尺、投影或图例——SIGMAI 会处理这些，并告诉您它做了什么。",
    "help_try_title": "可以从这些话开始",
    "help_try": "• “这个工程里打开了哪些图层？”\n• “把步道做成一张 A4 地图，我要打印。”\n• “公园地图，显示周边的市镇，再加一张小的位置图。”\n• “把各单元的名称标到地图上。”\n• “同一页放两张地图：公园和整个州。”\n• “这张地图能发表吗？还缺什么？”",
    "help_ask_title": "助手会问您的两件事",
    "help_ask": "数据来自哪里，以及谁署名这张地图。没有这两项信息，地图就不能在论文中引用，SIGMAI 也不会给出最高评级。地图的作者是您（或制作它的人），而不是这个插件。",
    "help_quality_title": "地图评级",
    "help_quality": "每张生成的地图都会得到 A 到 E 的评级，并列出问题所在以及每一项的修正方法。评级不是主观意见，而是一套明确的规则，每条规则都有其存在的理由。您可以让助手“解释一下这张地图的评级”。",
    "help_refuse_title": "SIGMAI 何时会拒绝",
    "help_refuse": "拒绝是有意为之。如果助手要求一种不存在的页面尺寸、一个空的标注字段，或者把文件夹当作文件，SIGMAI 会停下并说明它接受什么——而不是默默交出一张与要求不符的地图。",
    "help_privacy_title": "您的数据在哪里",
    "help_privacy": "桥接只在 127.0.0.1（也就是您自己的电脑）上监听，并且必须使用令牌。您的文件不会被发送到任何地方：助手发送命令，QGIS 在本机执行并返回结果。",
    "help_docs": "文档与代码：github.com/LuanCortesM/SIGMAI",
    # sobre
    "about_title": "关于 SIGMAI",
    "about_plugin": "插件作者：MACIEL, L. S. C. · herpetomantiqueira@gmail.com",
    "about_license": "SIGMAI {version} · GNU GPL v3.0 或更高版本 · github.com/LuanCortesM/SIGMAI",
    "about_map_authorship": "插件作者不是地图作者：请为每张生成的地图填写 map_author 和 data_source。",
    # diálogo de consentimento e mensagens do QGIS
    "consent_dialog_title": "AI 助手请求执行一项操作",
    "consent_allow": "允许一次",
    "consent_allow_category": "本次会话允许此类别的全部操作",
    "consent_deny": "拒绝",
    "msg_started": "SIGMAI 桥接已在 {host}:{port} 启动。",
    "msg_stopped": "SIGMAI 桥接已停止。",
    "msg_start_failed": "无法启动 SIGMAI 桥接",
    # idioma e aparência
    "language_label": "界面语言",
    "theme_label": "外观",
    "theme_auto": "自动（跟随 QGIS 主题）",
    "theme_light": "浅色",
    "theme_dark": "深色",
    # trilha de auditoria (aba Atividade)
    "event_allowed": "已允许",
    "event_denied_read_only": "已阻止（只读）",
    "event_denied_by_user": "被您拒绝",
    "event_denied_remembered": "已拒绝（此类别先前已被拒绝）",
    "event_denied_limit": "已阻止（会话上限）",
    "event_denied_output_root": "已阻止（文件夹未授权）",
    "event_denied_never_auto": "已阻止（需要您在面板中操作）",
    "event_denied_no_prompt": "已阻止（面板不可用）",
    "event_prompt_failed": "确认失败",
    "event_mode_changed": "访问模式已更改",
    "event_limit_changed": "上限已更改",
    "event_output_roots_changed": "授权文件夹已更改",
    "event_session_reset": "会话已重置",
    # categorias do consentimento — o nome canônico (registro) é o português
    "category_cartografia": "制图",
    "category_simbologia": "符号化",
    "category_camadas": "图层",
    "category_raster": "栅格",
    "category_vetor": "矢量",
    "category_selecao": "选择",
    "category_processing": "Processing",
    "category_fluxos": "工作流",
    "category_atlas": "图集与报告",
    "category_fontes": "数据源",
    "category_bancos": "数据库",
    "category_geometria": "几何",
    "category_expressoes": "表达式",
    "category_perfil": "作者档案",
    "category_gps": "GPS",
    "category_projeto": "项目",
    "category_desc_cartography": "创建布局、编排并导出地图",
    "category_desc_cartographic_design": "应用制图样式与配色",
    "category_desc_symbology": "更改图层的符号、颜色和标注",
    "category_desc_layers": "加载与导出图层",
    "category_desc_layer_tree": "重排、分组和移除工程中的图层",
    "category_desc_raster": "处理栅格并写入派生文件",
    "category_desc_vector": "生成新图层的几何运算",
    "category_desc_selection": "选择并提取要素",
    "category_desc_processing": "运行 QGIS Processing 算法",
    "category_desc_workflows": "运行组合工作流",
    "category_desc_atlas_reports": "生成图集、图幅系列和报告",
    "category_desc_data_sources": "连接服务并修复路径",
    "category_desc_databases": "连接数据库并加载表",
    "category_desc_crs_quality": "修复无效几何",
    "category_desc_expressions": "计算 QGIS 表达式",
    "category_desc_user_profile": "保存用户的作者档案",
    "category_desc_gps_gpx": "加载并转换 GPX 轨迹",
    "category_desc_project": "撤销助手在项目中的上一步操作",
    "category_desc_default": "修改工程或写入文件的操作",
    # resumo do pedido no diálogo de consentimento
    "consent_action": "操作",
    "consent_category": "类别",
    "consent_writes_to": "写入位置",
    "consent_params": "参数",
    # autoteste (passo 3)
    "selftest_bridge": "本地桥接",
    "selftest_auth": "身份验证",
    "selftest_project": "QGIS 工程",
    "selftest_session": "会话文件",
    "selftest_mcp": "MCP 服务器",
    "selftest_mode": "访问模式",
    "selftest_bridge_off": "桥接已停止。请在步骤 1 中启动。",
    "selftest_bridge_ok": "在 {host}:{port} 响应（插件 {version}）",
    "selftest_bridge_fail": "无响应：{error}",
    "selftest_auth_leak": "桥接接受了一个没有令牌的请求——这绝不应该发生",
    "selftest_auth_ok": "没有令牌的请求按预期被拒绝",
    "selftest_auth_http": "意外的 HTTP {code} 响应",
    "selftest_project_ok": "{count} 个图层，CRS {crs}",
    "selftest_crs_undefined": "未设置",
    "selftest_session_disabled": "已在“高级”中关闭；AI 客户端将无法自行找到桥接",
    "selftest_session_missing": "在 {path} 未找到",
    "selftest_session_unreadable": "无法读取：{error}",
    "selftest_session_port": "指向端口 {file_port}，但桥接运行在 {port}",
    "selftest_session_ok": "已写入，且与桥接一致",
    "selftest_mcp_missing": "文件缺失：{path}",
    "selftest_mcp_no_python": "未找到解释器：{executable}",
    "selftest_mcp_ok": "{server} 已就绪，使用 {python}",
    "selftest_mode_read_only": "只读：AI 可以检查和模拟，但不能生成地图。需要时可在“访问”标签页中更改。",
    # clientes de IA (passo 2)
    "client_generic_label": "其他 MCP 客户端",
    "client_path_claude_code": "工程根目录下的 .mcp.json，或 ~/.claude.json",
    "client_path_generic": "请查阅该客户端的文档",
    "client_note_claude_desktop": "Claude 菜单 → Settings… → Developer 标签页 → Edit Config。保存后，请完全退出 Claude Desktop 再重新打开。",
    "client_note_claude_code": "或者在工程目录内的终端中运行下面的命令。",
    "client_note_cursor": "Settings → MCP → Add new MCP server，或直接编辑该文件。",
    "client_note_codex": "把这段内容追加到配置文件末尾。",
    "client_note_generic": "任何通过 stdio 使用 MCP 的客户端都可以。约定是：以子进程方式启动下面的命令，并交换以换行分隔的 JSON-RPC 2.0。",
}
